package org.acra;

public enum ReportField {
    REPORT_ID,
    APP_VERSION_CODE,
    APP_VERSION_NAME,
    PACKAGE_NAME,
    FILE_PATH,
    PHONE_MODEL,
    ANDROID_VERSION,
    BUILD,
    BRAND,
    PRODUCT,
    TOTAL_MEM_SIZE,
    AVAILABLE_MEM_SIZE,
    CUSTOM_DATA,
    STACK_TRACE,
    INITIAL_CONFIGURATION,
    CRASH_CONFIGURATION,
    DISPLAY,
    USER_COMMENT,
    USER_APP_START_DATE,
    USER_CRASH_DATE,
    DUMPSYS_MEMINFO,
    DROPBOX,
    LOGCAT,
    EVENTSLOG,
    RADIOLOG,
    IS_SILENT,
    DEVICE_ID,
    INSTALLATION_ID,
    USER_EMAIL,
    DEVICE_FEATURES,
    ENVIRONMENT,
    SETTINGS_SYSTEM,
    SETTINGS_SECURE,
    SETTINGS_GLOBAL,
    SHARED_PREFERENCES,
    APPLICATION_LOG,
    MEDIA_CODEC_LIST,
    THREAD_DETAILS,
    USER_IP;

    static {
        REPORT_ID = new ReportField("REPORT_ID", 0);
        APP_VERSION_CODE = new ReportField("APP_VERSION_CODE", 1);
        APP_VERSION_NAME = new ReportField("APP_VERSION_NAME", 2);
        PACKAGE_NAME = new ReportField("PACKAGE_NAME", 3);
        FILE_PATH = new ReportField("FILE_PATH", 4);
        PHONE_MODEL = new ReportField("PHONE_MODEL", 5);
        ANDROID_VERSION = new ReportField("ANDROID_VERSION", 6);
        BUILD = new n("BUILD", 7);
        BRAND = new ReportField("BRAND", 8);
        PRODUCT = new ReportField("PRODUCT", 9);
        TOTAL_MEM_SIZE = new ReportField("TOTAL_MEM_SIZE", 10);
        AVAILABLE_MEM_SIZE = new ReportField("AVAILABLE_MEM_SIZE", 11);
        CUSTOM_DATA = new q("CUSTOM_DATA", 12);
        STACK_TRACE = new ReportField("STACK_TRACE", 13);
        INITIAL_CONFIGURATION = new r("INITIAL_CONFIGURATION", 14);
        CRASH_CONFIGURATION = new s("CRASH_CONFIGURATION", 15);
        DISPLAY = new t("DISPLAY", 16);
        USER_COMMENT = new ReportField("USER_COMMENT", 17);
        USER_APP_START_DATE = new ReportField("USER_APP_START_DATE", 18);
        USER_CRASH_DATE = new ReportField("USER_CRASH_DATE", 19);
        DUMPSYS_MEMINFO = new ReportField("DUMPSYS_MEMINFO", 20);
        DROPBOX = new ReportField("DROPBOX", 21);
        LOGCAT = new ReportField("LOGCAT", 22);
        EVENTSLOG = new ReportField("EVENTSLOG", 23);
        RADIOLOG = new ReportField("RADIOLOG", 24);
        IS_SILENT = new ReportField("IS_SILENT", 25);
        DEVICE_ID = new ReportField("DEVICE_ID", 26);
        INSTALLATION_ID = new ReportField("INSTALLATION_ID", 27);
        USER_EMAIL = new ReportField("USER_EMAIL", 28);
        DEVICE_FEATURES = new u("DEVICE_FEATURES", 29);
        ENVIRONMENT = new v("ENVIRONMENT", 30);
        SETTINGS_SYSTEM = new w("SETTINGS_SYSTEM", 31);
        SETTINGS_SECURE = new x("SETTINGS_SECURE", 32);
        SETTINGS_GLOBAL = new o("SETTINGS_GLOBAL", 33);
        SHARED_PREFERENCES = new p("SHARED_PREFERENCES", 34);
        APPLICATION_LOG = new ReportField("APPLICATION_LOG", 35);
        MEDIA_CODEC_LIST = new ReportField("MEDIA_CODEC_LIST", 36);
        THREAD_DETAILS = new ReportField("THREAD_DETAILS", 37);
        USER_IP = new ReportField("USER_IP", 38);
        ENUM$VALUES = new ReportField[]{REPORT_ID, APP_VERSION_CODE, APP_VERSION_NAME, PACKAGE_NAME, FILE_PATH, PHONE_MODEL, ANDROID_VERSION, BUILD, BRAND, PRODUCT, TOTAL_MEM_SIZE, AVAILABLE_MEM_SIZE, CUSTOM_DATA, STACK_TRACE, INITIAL_CONFIGURATION, CRASH_CONFIGURATION, DISPLAY, USER_COMMENT, USER_APP_START_DATE, USER_CRASH_DATE, DUMPSYS_MEMINFO, DROPBOX, LOGCAT, EVENTSLOG, RADIOLOG, IS_SILENT, DEVICE_ID, INSTALLATION_ID, USER_EMAIL, DEVICE_FEATURES, ENVIRONMENT, SETTINGS_SYSTEM, SETTINGS_SECURE, SETTINGS_GLOBAL, SHARED_PREFERENCES, APPLICATION_LOG, MEDIA_CODEC_LIST, THREAD_DETAILS, USER_IP};
    }

    public boolean containsKeyValuePairs() {
        return false;
    }
}