package com.actionbarsherlock;

public final class R {

    public final class anim {
        public static int view_transition_in_left;
        public static int view_transition_in_right;
        public static int view_transition_out_left;
        public static int view_transition_out_right;

        static {
            view_transition_in_left = 2130968576;
            view_transition_in_right = 2130968577;
            view_transition_out_left = 2130968578;
            view_transition_out_right = 2130968579;
        }
    }

    public final class array {
        public static int listArray;
        public static int listLongPressArray;
        public static int listLongPressValues;
        public static int listValues;

        static {
            listArray = 2131558400;
            listLongPressArray = 2131558402;
            listLongPressValues = 2131558403;
            listValues = 2131558401;
        }
    }

    public final class attr {
        public static int actionBarDivider;
        public static int actionBarItemBackground;
        public static int actionBarSize;
        public static int actionBarSplitStyle;
        public static int actionBarStyle;
        public static int actionBarTabBarStyle;
        public static int actionBarTabStyle;
        public static int actionBarTabTextStyle;
        public static int actionBarWidgetTheme;
        public static int actionButtonStyle;
        public static int actionDropDownStyle;
        public static int actionMenuTextAppearance;
        public static int actionMenuTextColor;
        public static int actionModeBackground;
        public static int actionModeCloseButtonStyle;
        public static int actionModeCloseDrawable;
        public static int actionModePopupWindowStyle;
        public static int actionModeShareDrawable;
        public static int actionModeSplitBackground;
        public static int actionModeStyle;
        public static int actionOverflowButtonStyle;
        public static int actionSpinnerItemStyle;
        public static int activatedBackgroundIndicator;
        public static int activityChooserViewStyle;
        public static int background;
        public static int backgroundSplit;
        public static int backgroundStacked;
        public static int buttonStyleSmall;
        public static int customNavigationLayout;
        public static int displayOptions;
        public static int divider;
        public static int dividerVertical;
        public static int dropDownHintAppearance;
        public static int dropDownListViewStyle;
        public static int dropdownListPreferredItemHeight;
        public static int expandActivityOverflowButtonDrawable;
        public static int headerBackground;
        public static int height;
        public static int homeAsUpIndicator;
        public static int homeLayout;
        public static int horizontalDivider;
        public static int icon;
        public static int iconifiedByDefault;
        public static int indeterminateProgressStyle;
        public static int initialActivityCount;
        public static int itemBackground;
        public static int itemIconDisabledAlpha;
        public static int itemPadding;
        public static int itemTextAppearance;
        public static int listPopupWindowStyle;
        public static int listPreferredItemHeightSmall;
        public static int listPreferredItemPaddingLeft;
        public static int listPreferredItemPaddingRight;
        public static int logo;
        public static int navigationMode;
        public static int popupMenuStyle;
        public static int preserveIconSpacing;
        public static int progressBarPadding;
        public static int progressBarStyle;
        public static int queryHint;
        public static int searchAutoCompleteTextView;
        public static int searchDropdownBackground;
        public static int searchResultListItemHeight;
        public static int searchViewCloseIcon;
        public static int searchViewEditQuery;
        public static int searchViewEditQueryBackground;
        public static int searchViewGoIcon;
        public static int searchViewSearchIcon;
        public static int searchViewTextField;
        public static int searchViewTextFieldRight;
        public static int searchViewVoiceIcon;
        public static int selectableItemBackground;
        public static int spinnerDropDownItemStyle;
        public static int spinnerItemStyle;
        public static int subtitle;
        public static int subtitleTextStyle;
        public static int textAppearanceLargePopupMenu;
        public static int textAppearanceListItemSmall;
        public static int textAppearanceSearchResultSubtitle;
        public static int textAppearanceSearchResultTitle;
        public static int textAppearanceSmall;
        public static int textAppearanceSmallPopupMenu;
        public static int textColorPrimary;
        public static int textColorPrimaryDisableOnly;
        public static int textColorPrimaryInverse;
        public static int textColorSearchUrl;
        public static int title;
        public static int titleTextStyle;
        public static int verticalDivider;
        public static int windowActionBar;
        public static int windowActionBarOverlay;
        public static int windowActionModeOverlay;
        public static int windowAnimationStyle;
        public static int windowContentOverlay;
        public static int windowMinWidthMajor;
        public static int windowMinWidthMinor;
        public static int windowNoTitle;
        public static int windowSplitActionBar;

        static {
            actionBarDivider = 2130771982;
            actionBarItemBackground = 2130771983;
            actionBarSize = 2130771981;
            actionBarSplitStyle = 2130771979;
            actionBarStyle = 2130771978;
            actionBarTabBarStyle = 2130771975;
            actionBarTabStyle = 2130771974;
            actionBarTabTextStyle = 2130771976;
            actionBarWidgetTheme = 2130771980;
            actionButtonStyle = 2130772026;
            actionDropDownStyle = 2130772025;
            actionMenuTextAppearance = 2130771984;
            actionMenuTextColor = 2130771985;
            actionModeBackground = 2130771988;
            actionModeCloseButtonStyle = 2130771987;
            actionModeCloseDrawable = 2130771990;
            actionModePopupWindowStyle = 2130771992;
            actionModeShareDrawable = 2130771991;
            actionModeSplitBackground = 2130771989;
            actionModeStyle = 2130771986;
            actionOverflowButtonStyle = 2130771977;
            actionSpinnerItemStyle = 2130772031;
            activatedBackgroundIndicator = 2130772039;
            activityChooserViewStyle = 2130772038;
            background = 2130771970;
            backgroundSplit = 2130771971;
            backgroundStacked = 2130772047;
            buttonStyleSmall = 2130771993;
            customNavigationLayout = 2130772048;
            displayOptions = 2130772042;
            divider = 2130771973;
            dividerVertical = 2130772024;
            dropDownHintAppearance = 2130772040;
            dropDownListViewStyle = 2130772028;
            dropdownListPreferredItemHeight = 2130772030;
            expandActivityOverflowButtonDrawable = 2130772063;
            headerBackground = 2130772057;
            height = 2130771972;
            homeAsUpIndicator = 2130772027;
            homeLayout = 2130772049;
            horizontalDivider = 2130772055;
            icon = 2130772045;
            iconifiedByDefault = 2130772064;
            indeterminateProgressStyle = 2130772051;
            initialActivityCount = 2130772062;
            itemBackground = 2130772058;
            itemIconDisabledAlpha = 2130772060;
            itemPadding = 2130772053;
            itemTextAppearance = 2130772054;
            listPopupWindowStyle = 2130772037;
            listPreferredItemHeightSmall = 2130772018;
            listPreferredItemPaddingLeft = 2130772019;
            listPreferredItemPaddingRight = 2130772020;
            logo = 2130772046;
            navigationMode = 2130772041;
            popupMenuStyle = 2130772029;
            preserveIconSpacing = 2130772061;
            progressBarPadding = 2130772052;
            progressBarStyle = 2130772050;
            queryHint = 2130772065;
            searchAutoCompleteTextView = 2130772004;
            searchDropdownBackground = 2130772005;
            searchResultListItemHeight = 2130772015;
            searchViewCloseIcon = 2130772006;
            searchViewEditQuery = 2130772010;
            searchViewEditQueryBackground = 2130772011;
            searchViewGoIcon = 2130772007;
            searchViewSearchIcon = 2130772008;
            searchViewTextField = 2130772012;
            searchViewTextFieldRight = 2130772013;
            searchViewVoiceIcon = 2130772009;
            selectableItemBackground = 2130771994;
            spinnerDropDownItemStyle = 2130772003;
            spinnerItemStyle = 2130772002;
            subtitle = 2130772044;
            subtitleTextStyle = 2130771969;
            textAppearanceLargePopupMenu = 2130771996;
            textAppearanceListItemSmall = 2130772021;
            textAppearanceSearchResultSubtitle = 2130772017;
            textAppearanceSearchResultTitle = 2130772016;
            textAppearanceSmall = 2130771998;
            textAppearanceSmallPopupMenu = 2130771997;
            textColorPrimary = 2130771999;
            textColorPrimaryDisableOnly = 2130772000;
            textColorPrimaryInverse = 2130772001;
            textColorSearchUrl = 2130772014;
            title = 2130772043;
            titleTextStyle = 2130771968;
            verticalDivider = 2130772056;
            windowActionBar = 2130772033;
            windowActionBarOverlay = 2130772034;
            windowActionModeOverlay = 2130772035;
            windowAnimationStyle = 2130772059;
            windowContentOverlay = 2130771995;
            windowMinWidthMajor = 2130772022;
            windowMinWidthMinor = 2130772023;
            windowNoTitle = 2130772032;
            windowSplitActionBar = 2130772036;
        }
    }

    public final class bool {
        public static int abs__action_bar_embed_tabs;
        public static int abs__action_bar_expanded_action_views_exclusive;
        public static int abs__config_actionMenuItemAllCaps;
        public static int abs__config_allowActionMenuItemTextWithIcon;
        public static int abs__config_showMenuShortcutsWhenKeyboardPresent;
        public static int abs__split_action_bar_is_narrow;

        static {
            abs__action_bar_embed_tabs = 2131165184;
            abs__action_bar_expanded_action_views_exclusive = 2131165186;
            abs__config_actionMenuItemAllCaps = 2131165188;
            abs__config_allowActionMenuItemTextWithIcon = 2131165189;
            abs__config_showMenuShortcutsWhenKeyboardPresent = 2131165187;
            abs__split_action_bar_is_narrow = 2131165185;
        }
    }

    public final class color {
        public static int abs__background_holo_dark;
        public static int abs__background_holo_light;
        public static int abs__bright_foreground_disabled_holo_dark;
        public static int abs__bright_foreground_disabled_holo_light;
        public static int abs__bright_foreground_holo_dark;
        public static int abs__bright_foreground_holo_light;
        public static int abs__primary_text_disable_only_holo_dark;
        public static int abs__primary_text_disable_only_holo_light;
        public static int abs__primary_text_holo_dark;
        public static int abs__primary_text_holo_light;

        static {
            abs__background_holo_dark = 2131230720;
            abs__background_holo_light = 2131230721;
            abs__bright_foreground_disabled_holo_dark = 2131230724;
            abs__bright_foreground_disabled_holo_light = 2131230725;
            abs__bright_foreground_holo_dark = 2131230722;
            abs__bright_foreground_holo_light = 2131230723;
            abs__primary_text_disable_only_holo_dark = 2131230726;
            abs__primary_text_disable_only_holo_light = 2131230727;
            abs__primary_text_holo_dark = 2131230728;
            abs__primary_text_holo_light = 2131230729;
        }
    }

    public final class dimen {
        public static int abs__action_bar_default_height;
        public static int abs__action_bar_icon_vertical_padding;
        public static int abs__action_bar_subtitle_bottom_margin;
        public static int abs__action_bar_subtitle_text_size;
        public static int abs__action_bar_subtitle_top_margin;
        public static int abs__action_bar_title_text_size;
        public static int abs__action_button_min_width;
        public static int abs__config_prefDialogWidth;
        public static int abs__dialog_min_width_major;
        public static int abs__dialog_min_width_minor;
        public static int abs__dropdownitem_icon_width;
        public static int abs__dropdownitem_text_padding_left;
        public static int abs__dropdownitem_text_padding_right;
        public static int abs__search_view_preferred_width;
        public static int abs__search_view_text_min_width;

        static {
            abs__action_bar_default_height = 2131296257;
            abs__action_bar_icon_vertical_padding = 2131296258;
            abs__action_bar_subtitle_bottom_margin = 2131296262;
            abs__action_bar_subtitle_text_size = 2131296260;
            abs__action_bar_subtitle_top_margin = 2131296261;
            abs__action_bar_title_text_size = 2131296259;
            abs__action_button_min_width = 2131296263;
            abs__config_prefDialogWidth = 2131296256;
            abs__dialog_min_width_major = 2131296269;
            abs__dialog_min_width_minor = 2131296270;
            abs__dropdownitem_icon_width = 2131296266;
            abs__dropdownitem_text_padding_left = 2131296264;
            abs__dropdownitem_text_padding_right = 2131296265;
            abs__search_view_preferred_width = 2131296268;
            abs__search_view_text_min_width = 2131296267;
        }
    }

    public final class drawable {
        public static int abs__ab_bottom_solid_dark_holo;
        public static int abs__ab_bottom_solid_inverse_holo;
        public static int abs__ab_bottom_solid_light_holo;
        public static int abs__ab_bottom_transparent_dark_holo;
        public static int abs__ab_bottom_transparent_light_holo;
        public static int abs__ab_share_pack_holo_dark;
        public static int abs__ab_share_pack_holo_light;
        public static int abs__ab_solid_dark_holo;
        public static int abs__ab_solid_light_holo;
        public static int abs__ab_solid_shadow_holo;
        public static int abs__ab_stacked_solid_dark_holo;
        public static int abs__ab_stacked_solid_light_holo;
        public static int abs__ab_stacked_transparent_dark_holo;
        public static int abs__ab_stacked_transparent_light_holo;
        public static int abs__ab_transparent_dark_holo;
        public static int abs__ab_transparent_light_holo;
        public static int abs__activated_background_holo_dark;
        public static int abs__activated_background_holo_light;
        public static int abs__btn_cab_done_default_holo_dark;
        public static int abs__btn_cab_done_default_holo_light;
        public static int abs__btn_cab_done_focused_holo_dark;
        public static int abs__btn_cab_done_focused_holo_light;
        public static int abs__btn_cab_done_holo_dark;
        public static int abs__btn_cab_done_holo_light;
        public static int abs__btn_cab_done_pressed_holo_dark;
        public static int abs__btn_cab_done_pressed_holo_light;
        public static int abs__cab_background_bottom_holo_dark;
        public static int abs__cab_background_bottom_holo_light;
        public static int abs__cab_background_top_holo_dark;
        public static int abs__cab_background_top_holo_light;
        public static int abs__ic_ab_back_holo_dark;
        public static int abs__ic_ab_back_holo_light;
        public static int abs__ic_cab_done_holo_dark;
        public static int abs__ic_cab_done_holo_light;
        public static int abs__ic_clear;
        public static int abs__ic_clear_disabled;
        public static int abs__ic_clear_holo_light;
        public static int abs__ic_clear_normal;
        public static int abs__ic_clear_search_api_disabled_holo_light;
        public static int abs__ic_clear_search_api_holo_light;
        public static int abs__ic_commit_search_api_holo_dark;
        public static int abs__ic_commit_search_api_holo_light;
        public static int abs__ic_go;
        public static int abs__ic_go_search_api_holo_light;
        public static int abs__ic_menu_moreoverflow_holo_dark;
        public static int abs__ic_menu_moreoverflow_holo_light;
        public static int abs__ic_menu_moreoverflow_normal_holo_dark;
        public static int abs__ic_menu_moreoverflow_normal_holo_light;
        public static int abs__ic_menu_share_holo_dark;
        public static int abs__ic_menu_share_holo_light;
        public static int abs__ic_search;
        public static int abs__ic_search_api_holo_light;
        public static int abs__ic_voice_search;
        public static int abs__ic_voice_search_api_holo_light;
        public static int abs__item_background_holo_dark;
        public static int abs__item_background_holo_light;
        public static int abs__list_activated_holo;
        public static int abs__list_checked_holo_dark;
        public static int abs__list_divider_holo_dark;
        public static int abs__list_divider_holo_light;
        public static int abs__list_focused_holo;
        public static int abs__list_longpressed_holo;
        public static int abs__list_pressed_holo_dark;
        public static int abs__list_pressed_holo_light;
        public static int abs__list_selector_background_transition_holo_dark;
        public static int abs__list_selector_background_transition_holo_light;
        public static int abs__list_selector_disabled_holo_dark;
        public static int abs__list_selector_disabled_holo_light;
        public static int abs__list_selector_holo_dark;
        public static int abs__list_selector_holo_light;
        public static int abs__menu_dropdown_panel_holo_dark;
        public static int abs__menu_dropdown_panel_holo_light;
        public static int abs__progress_bg_holo_dark;
        public static int abs__progress_bg_holo_light;
        public static int abs__progress_horizontal_holo_dark;
        public static int abs__progress_horizontal_holo_light;
        public static int abs__progress_medium_holo;
        public static int abs__progress_primary_holo_dark;
        public static int abs__progress_primary_holo_light;
        public static int abs__progress_secondary_holo_dark;
        public static int abs__progress_secondary_holo_light;
        public static int abs__search_dropdown_dark;
        public static int abs__search_dropdown_light;
        public static int abs__spinner_48_inner_holo;
        public static int abs__spinner_48_outer_holo;
        public static int abs__spinner_ab_default_holo_dark;
        public static int abs__spinner_ab_default_holo_light;
        public static int abs__spinner_ab_disabled_holo_dark;
        public static int abs__spinner_ab_disabled_holo_light;
        public static int abs__spinner_ab_focused_holo_dark;
        public static int abs__spinner_ab_focused_holo_light;
        public static int abs__spinner_ab_holo_dark;
        public static int abs__spinner_ab_holo_light;
        public static int abs__spinner_ab_pressed_holo_dark;
        public static int abs__spinner_ab_pressed_holo_light;
        public static int abs__tab_indicator_ab_holo;
        public static int abs__tab_selected_focused_holo;
        public static int abs__tab_selected_holo;
        public static int abs__tab_selected_pressed_holo;
        public static int abs__tab_unselected_pressed_holo;
        public static int abs__textfield_search_default_holo_dark;
        public static int abs__textfield_search_default_holo_light;
        public static int abs__textfield_search_right_default_holo_dark;
        public static int abs__textfield_search_right_default_holo_light;
        public static int abs__textfield_search_right_selected_holo_dark;
        public static int abs__textfield_search_right_selected_holo_light;
        public static int abs__textfield_search_selected_holo_dark;
        public static int abs__textfield_search_selected_holo_light;
        public static int abs__textfield_searchview_holo_dark;
        public static int abs__textfield_searchview_holo_light;
        public static int abs__textfield_searchview_right_holo_dark;
        public static int abs__textfield_searchview_right_holo_light;
        public static int abs__toast_frame;
        public static int add;
        public static int back;
        public static int button_black;
        public static int button_black_disabled;
        public static int button_black_normal;
        public static int button_black_pressed;
        public static int button_light;
        public static int button_light_disabled;
        public static int button_light_normal;
        public static int button_light_pressed;
        public static int button_orange;
        public static int button_orange_disabled;
        public static int button_orange_normal;
        public static int button_orange_pressed;
        public static int button_pink;
        public static int button_pink_disabled;
        public static int button_pink_normal;
        public static int button_pink_pressed;
        public static int catheader_black;
        public static int catheader_black_normal;
        public static int catheader_black_pressed;
        public static int catheader_light;
        public static int catheader_light_normal;
        public static int catheader_light_pressed;
        public static int catheader_orange;
        public static int catheader_orange_normal;
        public static int catheader_orange_pressed;
        public static int catheader_pink;
        public static int catheader_pink_normal;
        public static int catheader_pink_pressed;
        public static int cursor_black;
        public static int cursor_light;
        public static int cursor_orange;
        public static int cursor_pink;
        public static int fav;
        public static int ic_content_new;
        public static int ic_content_remove;
        public static int ic_menu_moreoverflow_normal_holo_dark;
        public static int ic_navigation_back;
        public static int ic_navigation_forward;
        public static int icon;
        public static int micon;
        public static int next;
        public static int nicon;
        public static int nicon2;
        public static int pencil;
        public static int previous;
        public static int remove;
        public static int sad;
        public static int smile;
        public static int smileu;
        public static int step1;
        public static int step2;
        public static int step3;
        public static int step4;

        static {
            abs__ab_bottom_solid_dark_holo = 2130837504;
            abs__ab_bottom_solid_inverse_holo = 2130837505;
            abs__ab_bottom_solid_light_holo = 2130837506;
            abs__ab_bottom_transparent_dark_holo = 2130837507;
            abs__ab_bottom_transparent_light_holo = 2130837508;
            abs__ab_share_pack_holo_dark = 2130837509;
            abs__ab_share_pack_holo_light = 2130837510;
            abs__ab_solid_dark_holo = 2130837511;
            abs__ab_solid_light_holo = 2130837512;
            abs__ab_solid_shadow_holo = 2130837513;
            abs__ab_stacked_solid_dark_holo = 2130837514;
            abs__ab_stacked_solid_light_holo = 2130837515;
            abs__ab_stacked_transparent_dark_holo = 2130837516;
            abs__ab_stacked_transparent_light_holo = 2130837517;
            abs__ab_transparent_dark_holo = 2130837518;
            abs__ab_transparent_light_holo = 2130837519;
            abs__activated_background_holo_dark = 2130837520;
            abs__activated_background_holo_light = 2130837521;
            abs__btn_cab_done_default_holo_dark = 2130837522;
            abs__btn_cab_done_default_holo_light = 2130837523;
            abs__btn_cab_done_focused_holo_dark = 2130837524;
            abs__btn_cab_done_focused_holo_light = 2130837525;
            abs__btn_cab_done_holo_dark = 2130837526;
            abs__btn_cab_done_holo_light = 2130837527;
            abs__btn_cab_done_pressed_holo_dark = 2130837528;
            abs__btn_cab_done_pressed_holo_light = 2130837529;
            abs__cab_background_bottom_holo_dark = 2130837530;
            abs__cab_background_bottom_holo_light = 2130837531;
            abs__cab_background_top_holo_dark = 2130837532;
            abs__cab_background_top_holo_light = 2130837533;
            abs__ic_ab_back_holo_dark = 2130837534;
            abs__ic_ab_back_holo_light = 2130837535;
            abs__ic_cab_done_holo_dark = 2130837536;
            abs__ic_cab_done_holo_light = 2130837537;
            abs__ic_clear = 2130837538;
            abs__ic_clear_disabled = 2130837539;
            abs__ic_clear_holo_light = 2130837540;
            abs__ic_clear_normal = 2130837541;
            abs__ic_clear_search_api_disabled_holo_light = 2130837542;
            abs__ic_clear_search_api_holo_light = 2130837543;
            abs__ic_commit_search_api_holo_dark = 2130837544;
            abs__ic_commit_search_api_holo_light = 2130837545;
            abs__ic_go = 2130837546;
            abs__ic_go_search_api_holo_light = 2130837547;
            abs__ic_menu_moreoverflow_holo_dark = 2130837548;
            abs__ic_menu_moreoverflow_holo_light = 2130837549;
            abs__ic_menu_moreoverflow_normal_holo_dark = 2130837550;
            abs__ic_menu_moreoverflow_normal_holo_light = 2130837551;
            abs__ic_menu_share_holo_dark = 2130837552;
            abs__ic_menu_share_holo_light = 2130837553;
            abs__ic_search = 2130837554;
            abs__ic_search_api_holo_light = 2130837555;
            abs__ic_voice_search = 2130837556;
            abs__ic_voice_search_api_holo_light = 2130837557;
            abs__item_background_holo_dark = 2130837558;
            abs__item_background_holo_light = 2130837559;
            abs__list_activated_holo = 2130837560;
            abs__list_checked_holo_dark = 2130837561;
            abs__list_divider_holo_dark = 2130837562;
            abs__list_divider_holo_light = 2130837563;
            abs__list_focused_holo = 2130837564;
            abs__list_longpressed_holo = 2130837565;
            abs__list_pressed_holo_dark = 2130837566;
            abs__list_pressed_holo_light = 2130837567;
            abs__list_selector_background_transition_holo_dark = 2130837568;
            abs__list_selector_background_transition_holo_light = 2130837569;
            abs__list_selector_disabled_holo_dark = 2130837570;
            abs__list_selector_disabled_holo_light = 2130837571;
            abs__list_selector_holo_dark = 2130837572;
            abs__list_selector_holo_light = 2130837573;
            abs__menu_dropdown_panel_holo_dark = 2130837574;
            abs__menu_dropdown_panel_holo_light = 2130837575;
            abs__progress_bg_holo_dark = 2130837576;
            abs__progress_bg_holo_light = 2130837577;
            abs__progress_horizontal_holo_dark = 2130837578;
            abs__progress_horizontal_holo_light = 2130837579;
            abs__progress_medium_holo = 2130837580;
            abs__progress_primary_holo_dark = 2130837581;
            abs__progress_primary_holo_light = 2130837582;
            abs__progress_secondary_holo_dark = 2130837583;
            abs__progress_secondary_holo_light = 2130837584;
            abs__search_dropdown_dark = 2130837585;
            abs__search_dropdown_light = 2130837586;
            abs__spinner_48_inner_holo = 2130837587;
            abs__spinner_48_outer_holo = 2130837588;
            abs__spinner_ab_default_holo_dark = 2130837589;
            abs__spinner_ab_default_holo_light = 2130837590;
            abs__spinner_ab_disabled_holo_dark = 2130837591;
            abs__spinner_ab_disabled_holo_light = 2130837592;
            abs__spinner_ab_focused_holo_dark = 2130837593;
            abs__spinner_ab_focused_holo_light = 2130837594;
            abs__spinner_ab_holo_dark = 2130837595;
            abs__spinner_ab_holo_light = 2130837596;
            abs__spinner_ab_pressed_holo_dark = 2130837597;
            abs__spinner_ab_pressed_holo_light = 2130837598;
            abs__tab_indicator_ab_holo = 2130837599;
            abs__tab_selected_focused_holo = 2130837600;
            abs__tab_selected_holo = 2130837601;
            abs__tab_selected_pressed_holo = 2130837602;
            abs__tab_unselected_pressed_holo = 2130837603;
            abs__textfield_search_default_holo_dark = 2130837604;
            abs__textfield_search_default_holo_light = 2130837605;
            abs__textfield_search_right_default_holo_dark = 2130837606;
            abs__textfield_search_right_default_holo_light = 2130837607;
            abs__textfield_search_right_selected_holo_dark = 2130837608;
            abs__textfield_search_right_selected_holo_light = 2130837609;
            abs__textfield_search_selected_holo_dark = 2130837610;
            abs__textfield_search_selected_holo_light = 2130837611;
            abs__textfield_searchview_holo_dark = 2130837612;
            abs__textfield_searchview_holo_light = 2130837613;
            abs__textfield_searchview_right_holo_dark = 2130837614;
            abs__textfield_searchview_right_holo_light = 2130837615;
            abs__toast_frame = 2130837616;
            add = 2130837617;
            back = 2130837618;
            button_black = 2130837619;
            button_black_disabled = 2130837620;
            button_black_normal = 2130837621;
            button_black_pressed = 2130837622;
            button_light = 2130837623;
            button_light_disabled = 2130837624;
            button_light_normal = 2130837625;
            button_light_pressed = 2130837626;
            button_orange = 2130837627;
            button_orange_disabled = 2130837628;
            button_orange_normal = 2130837629;
            button_orange_pressed = 2130837630;
            button_pink = 2130837631;
            button_pink_disabled = 2130837632;
            button_pink_normal = 2130837633;
            button_pink_pressed = 2130837634;
            catheader_black = 2130837635;
            catheader_black_normal = 2130837636;
            catheader_black_pressed = 2130837637;
            catheader_light = 2130837638;
            catheader_light_normal = 2130837639;
            catheader_light_pressed = 2130837640;
            catheader_orange = 2130837641;
            catheader_orange_normal = 2130837642;
            catheader_orange_pressed = 2130837643;
            catheader_pink = 2130837644;
            catheader_pink_normal = 2130837645;
            catheader_pink_pressed = 2130837646;
            cursor_black = 2130837647;
            cursor_light = 2130837648;
            cursor_orange = 2130837649;
            cursor_pink = 2130837650;
            fav = 2130837651;
            ic_content_new = 2130837652;
            ic_content_remove = 2130837653;
            ic_menu_moreoverflow_normal_holo_dark = 2130837654;
            ic_navigation_back = 2130837655;
            ic_navigation_forward = 2130837656;
            icon = 2130837657;
            micon = 2130837658;
            next = 2130837659;
            nicon = 2130837660;
            nicon2 = 2130837661;
            pencil = 2130837662;
            previous = 2130837663;
            remove = 2130837664;
            sad = 2130837665;
            smile = 2130837666;
            smileu = 2130837667;
            step1 = 2130837668;
            step2 = 2130837669;
            step3 = 2130837670;
            step4 = 2130837671;
        }
    }

    public final class id {
        public static int abs__action_bar;
        public static int abs__action_bar_container;
        public static int abs__action_bar_subtitle;
        public static int abs__action_bar_title;
        public static int abs__action_context_bar;
        public static int abs__action_menu_divider;
        public static int abs__action_menu_presenter;
        public static int abs__action_mode_bar;
        public static int abs__action_mode_bar_stub;
        public static int abs__action_mode_close_button;
        public static int abs__activity_chooser_view_content;
        public static int abs__checkbox;
        public static int abs__content;
        public static int abs__default_activity_button;
        public static int abs__expand_activities_button;
        public static int abs__home;
        public static int abs__icon;
        public static int abs__image;
        public static int abs__imageButton;
        public static int abs__list_item;
        public static int abs__progress_circular;
        public static int abs__progress_horizontal;
        public static int abs__radio;
        public static int abs__search_badge;
        public static int abs__search_bar;
        public static int abs__search_button;
        public static int abs__search_close_btn;
        public static int abs__search_edit_frame;
        public static int abs__search_go_btn;
        public static int abs__search_mag_icon;
        public static int abs__search_plate;
        public static int abs__search_src_text;
        public static int abs__search_voice_btn;
        public static int abs__shortcut;
        public static int abs__split_action_bar;
        public static int abs__submit_area;
        public static int abs__textButton;
        public static int abs__title;
        public static int abs__up;
        public static int adView;
        public static int bottom_panel;
        public static int button_1;
        public static int button_2;
        public static int button_3;
        public static int button_4;
        public static int button_5;
        public static int button_6;
        public static int disableHome;
        public static int edit_query;
        public static int homeAsUp;
        public static int list;
        public static int listMode;
        public static int menu;
        public static int normal;
        public static int showCustom;
        public static int showHome;
        public static int showTitle;
        public static int tabMode;
        public static int useLogo;
        public static int viewPager;
        public static int wrap_content;

        static {
            abs__action_bar = 2131099680;
            abs__action_bar_container = 2131099679;
            abs__action_bar_subtitle = 2131099665;
            abs__action_bar_title = 2131099664;
            abs__action_context_bar = 2131099681;
            abs__action_menu_divider = 2131099660;
            abs__action_menu_presenter = 2131099661;
            abs__action_mode_bar = 2131099685;
            abs__action_mode_bar_stub = 2131099684;
            abs__action_mode_close_button = 2131099668;
            abs__activity_chooser_view_content = 2131099669;
            abs__checkbox = 2131099676;
            abs__content = 2131099682;
            abs__default_activity_button = 2131099672;
            abs__expand_activities_button = 2131099670;
            abs__home = 2131099658;
            abs__icon = 2131099674;
            abs__image = 2131099671;
            abs__imageButton = 2131099666;
            abs__list_item = 2131099673;
            abs__progress_circular = 2131099662;
            abs__progress_horizontal = 2131099663;
            abs__radio = 2131099677;
            abs__search_badge = 2131099688;
            abs__search_bar = 2131099687;
            abs__search_button = 2131099689;
            abs__search_close_btn = 2131099694;
            abs__search_edit_frame = 2131099690;
            abs__search_go_btn = 2131099696;
            abs__search_mag_icon = 2131099691;
            abs__search_plate = 2131099692;
            abs__search_src_text = 2131099693;
            abs__search_voice_btn = 2131099697;
            abs__shortcut = 2131099678;
            abs__split_action_bar = 2131099683;
            abs__submit_area = 2131099695;
            abs__textButton = 2131099667;
            abs__title = 2131099675;
            abs__up = 2131099659;
            adView = 2131099699;
            bottom_panel = 2131099702;
            button_1 = 2131099703;
            button_2 = 2131099704;
            button_3 = 2131099705;
            button_4 = 2131099706;
            button_5 = 2131099707;
            button_6 = 2131099708;
            disableHome = 2131099657;
            edit_query = 2131099686;
            homeAsUp = 2131099654;
            list = 2131099698;
            listMode = 2131099650;
            menu = 2131099701;
            normal = 2131099649;
            showCustom = 2131099656;
            showHome = 2131099653;
            showTitle = 2131099655;
            tabMode = 2131099651;
            useLogo = 2131099652;
            viewPager = 2131099700;
            wrap_content = 2131099648;
        }
    }

    public final class integer {
        public static int abs__max_action_buttons;

        static {
            abs__max_action_buttons = 2131361792;
        }
    }

    public final class layout {
        public static int abs__action_bar_home;
        public static int abs__action_bar_tab;
        public static int abs__action_bar_tab_bar_view;
        public static int abs__action_bar_title_item;
        public static int abs__action_menu_item_layout;
        public static int abs__action_menu_layout;
        public static int abs__action_mode_bar;
        public static int abs__action_mode_close_item;
        public static int abs__activity_chooser_view;
        public static int abs__activity_chooser_view_list_item;
        public static int abs__list_menu_item_checkbox;
        public static int abs__list_menu_item_icon;
        public static int abs__list_menu_item_radio;
        public static int abs__popup_menu_item_layout;
        public static int abs__screen_action_bar;
        public static int abs__screen_action_bar_overlay;
        public static int abs__screen_simple;
        public static int abs__screen_simple_overlay_action_mode;
        public static int abs__search_dropdown_item_icons_2line;
        public static int abs__search_view;
        public static int abs__simple_dropdown_hint;
        public static int dragitem;
        public static int editor;
        public static int main;
        public static int sherlock_spinner_dropdown_item;
        public static int sherlock_spinner_item;
        public static int tutorial;

        static {
            abs__action_bar_home = 2130903040;
            abs__action_bar_tab = 2130903041;
            abs__action_bar_tab_bar_view = 2130903042;
            abs__action_bar_title_item = 2130903043;
            abs__action_menu_item_layout = 2130903044;
            abs__action_menu_layout = 2130903045;
            abs__action_mode_bar = 2130903046;
            abs__action_mode_close_item = 2130903047;
            abs__activity_chooser_view = 2130903048;
            abs__activity_chooser_view_list_item = 2130903049;
            abs__list_menu_item_checkbox = 2130903050;
            abs__list_menu_item_icon = 2130903051;
            abs__list_menu_item_radio = 2130903052;
            abs__popup_menu_item_layout = 2130903053;
            abs__screen_action_bar = 2130903054;
            abs__screen_action_bar_overlay = 2130903055;
            abs__screen_simple = 2130903056;
            abs__screen_simple_overlay_action_mode = 2130903057;
            abs__search_dropdown_item_icons_2line = 2130903058;
            abs__search_view = 2130903059;
            abs__simple_dropdown_hint = 2130903060;
            dragitem = 2130903061;
            editor = 2130903062;
            main = 2130903063;
            sherlock_spinner_dropdown_item = 2130903064;
            sherlock_spinner_item = 2130903065;
            tutorial = 2130903066;
        }
    }

    public final class string {
        public static int about;
        public static int abs__action_bar_home_description;
        public static int abs__action_bar_up_description;
        public static int abs__action_menu_overflow_description;
        public static int abs__action_mode_done;
        public static int abs__activity_chooser_view_see_all;
        public static int abs__activitychooserview_choose_application;
        public static int abs__searchview_description_clear;
        public static int abs__searchview_description_query;
        public static int abs__searchview_description_search;
        public static int abs__searchview_description_submit;
        public static int abs__searchview_description_voice;
        public static int abs__shareactionprovider_share_with;
        public static int abs__shareactionprovider_share_with_application;
        public static int action_clipboard;
        public static int action_favorites;
        public static int add_spaces;
        public static int add_spaces_t;
        public static int added;
        public static int app_launcher;
        public static int app_name;
        public static int back;
        public static int clear_clipboard;
        public static int close;
        public static int copied;
        public static int editor;
        public static int export_c;
        public static int export_t;
        public static int exported;
        public static int exporting;
        public static int hide_after;
        public static int hide_after_t;
        public static int iface;
        public static int import_c;
        public static int import_t;
        public static int imported;
        public static int importexport;
        public static int importing;
        public static int input_emoticon;
        public static int long_press;
        public static int long_press_t;
        public static int next;
        public static int notavailable_reading;
        public static int notavailable_writing;
        public static int old_icon;
        public static int old_icon_t;
        public static int oldstyle_fourpage;
        public static int oldstyle_fourpage_t;
        public static int other;
        public static int selection;
        public static int settings;
        public static int show_notification;
        public static int show_notification_t;
        public static int show_tabs;
        public static int show_tabs_t;
        public static int show_tutorial;
        public static int step1;
        public static int step2;
        public static int step3;
        public static int step4;
        public static int theme;
        public static int theme_black;
        public static int theme_light;
        public static int theme_orange;
        public static int theme_pink;
        public static int theme_t;
        public static int toast_after;
        public static int toast_after_t;
        public static int tutorial;

        static {
            about = 2131427348;
            abs__action_bar_home_description = 2131427328;
            abs__action_bar_up_description = 2131427329;
            abs__action_menu_overflow_description = 2131427330;
            abs__action_mode_done = 2131427331;
            abs__activity_chooser_view_see_all = 2131427332;
            abs__activitychooserview_choose_application = 2131427333;
            abs__searchview_description_clear = 2131427338;
            abs__searchview_description_query = 2131427337;
            abs__searchview_description_search = 2131427336;
            abs__searchview_description_submit = 2131427339;
            abs__searchview_description_voice = 2131427340;
            abs__shareactionprovider_share_with = 2131427334;
            abs__shareactionprovider_share_with_application = 2131427335;
            action_clipboard = 2131427370;
            action_favorites = 2131427369;
            add_spaces = 2131427365;
            add_spaces_t = 2131427366;
            added = 2131427344;
            app_launcher = 2131427342;
            app_name = 2131427341;
            back = 2131427362;
            clear_clipboard = 2131427392;
            close = 2131427346;
            copied = 2131427343;
            editor = 2131427345;
            export_c = 2131427380;
            export_t = 2131427381;
            exported = 2131427388;
            exporting = 2131427386;
            hide_after = 2131427351;
            hide_after_t = 2131427352;
            iface = 2131427378;
            import_c = 2131427382;
            import_t = 2131427383;
            imported = 2131427389;
            importexport = 2131427379;
            importing = 2131427387;
            input_emoticon = 2131427355;
            long_press = 2131427367;
            long_press_t = 2131427368;
            next = 2131427361;
            notavailable_reading = 2131427385;
            notavailable_writing = 2131427384;
            old_icon = 2131427371;
            old_icon_t = 2131427372;
            oldstyle_fourpage = 2131427356;
            oldstyle_fourpage_t = 2131427357;
            other = 2131427390;
            selection = 2131427377;
            settings = 2131427347;
            show_notification = 2131427349;
            show_notification_t = 2131427350;
            show_tabs = 2131427363;
            show_tabs_t = 2131427364;
            show_tutorial = 2131427391;
            step1 = 2131427393;
            step2 = 2131427394;
            step3 = 2131427395;
            step4 = 2131427396;
            theme = 2131427358;
            theme_black = 2131427374;
            theme_light = 2131427373;
            theme_orange = 2131427375;
            theme_pink = 2131427376;
            theme_t = 2131427359;
            toast_after = 2131427353;
            toast_after_t = 2131427354;
            tutorial = 2131427360;
        }
    }

    public final class style {
        public static int Black;
        public static int ButtonBlack;
        public static int ButtonLight;
        public static int ButtonOrange;
        public static int ButtonPink;
        public static int Light;
        public static int Orange;
        public static int Pink;
        public static int Sherlock___TextAppearance_Small;
        public static int Sherlock___Theme;
        public static int Sherlock___Theme_DarkActionBar;
        public static int Sherlock___Theme_Light;
        public static int Sherlock___Widget_ActionBar;
        public static int Sherlock___Widget_ActionMode;
        public static int Sherlock___Widget_ActivityChooserView;
        public static int Sherlock___Widget_Holo_DropDownItem;
        public static int Sherlock___Widget_Holo_ListView;
        public static int Sherlock___Widget_Holo_Spinner;
        public static int Sherlock___Widget_SearchAutoCompleteTextView;
        public static int TextAppearance_Sherlock;
        public static int TextAppearance_Sherlock_Light_SearchResult;
        public static int TextAppearance_Sherlock_Light_SearchResult_Subtitle;
        public static int TextAppearance_Sherlock_Light_SearchResult_Title;
        public static int TextAppearance_Sherlock_Light_Small;
        public static int TextAppearance_Sherlock_Light_Widget_PopupMenu_Large;
        public static int TextAppearance_Sherlock_Light_Widget_PopupMenu_Small;
        public static int TextAppearance_Sherlock_SearchResult;
        public static int TextAppearance_Sherlock_SearchResult_Subtitle;
        public static int TextAppearance_Sherlock_SearchResult_Title;
        public static int TextAppearance_Sherlock_Small;
        public static int TextAppearance_Sherlock_Widget_ActionBar_Menu;
        public static int TextAppearance_Sherlock_Widget_ActionBar_Subtitle;
        public static int TextAppearance_Sherlock_Widget_ActionBar_Subtitle_Inverse;
        public static int TextAppearance_Sherlock_Widget_ActionBar_Title;
        public static int TextAppearance_Sherlock_Widget_ActionBar_Title_Inverse;
        public static int TextAppearance_Sherlock_Widget_ActionMode_Subtitle;
        public static int TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse;
        public static int TextAppearance_Sherlock_Widget_ActionMode_Title;
        public static int TextAppearance_Sherlock_Widget_ActionMode_Title_Inverse;
        public static int TextAppearance_Sherlock_Widget_DropDownHint;
        public static int TextAppearance_Sherlock_Widget_DropDownItem;
        public static int TextAppearance_Sherlock_Widget_PopupMenu;
        public static int TextAppearance_Sherlock_Widget_PopupMenu_Large;
        public static int TextAppearance_Sherlock_Widget_PopupMenu_Small;
        public static int TextAppearance_Sherlock_Widget_TextView_SpinnerItem;
        public static int Theme_Sherlock;
        public static int Theme_Sherlock_Light;
        public static int Theme_Sherlock_Light_DarkActionBar;
        public static int Theme_Sherlock_Light_NoActionBar;
        public static int Theme_Sherlock_NoActionBar;
        public static int Widget;
        public static int Widget_Sherlock_ActionBar;
        public static int Widget_Sherlock_ActionBar_Solid;
        public static int Widget_Sherlock_ActionBar_TabBar;
        public static int Widget_Sherlock_ActionBar_TabText;
        public static int Widget_Sherlock_ActionBar_TabView;
        public static int Widget_Sherlock_ActionButton;
        public static int Widget_Sherlock_ActionButton_CloseMode;
        public static int Widget_Sherlock_ActionButton_Overflow;
        public static int Widget_Sherlock_ActionMode;
        public static int Widget_Sherlock_ActivityChooserView;
        public static int Widget_Sherlock_Button_Small;
        public static int Widget_Sherlock_DropDownItem_Spinner;
        public static int Widget_Sherlock_Light_ActionBar;
        public static int Widget_Sherlock_Light_ActionBar_Solid;
        public static int Widget_Sherlock_Light_ActionBar_Solid_Inverse;
        public static int Widget_Sherlock_Light_ActionBar_TabBar;
        public static int Widget_Sherlock_Light_ActionBar_TabBar_Inverse;
        public static int Widget_Sherlock_Light_ActionBar_TabText;
        public static int Widget_Sherlock_Light_ActionBar_TabText_Inverse;
        public static int Widget_Sherlock_Light_ActionBar_TabView;
        public static int Widget_Sherlock_Light_ActionBar_TabView_Inverse;
        public static int Widget_Sherlock_Light_ActionButton;
        public static int Widget_Sherlock_Light_ActionButton_CloseMode;
        public static int Widget_Sherlock_Light_ActionButton_Overflow;
        public static int Widget_Sherlock_Light_ActionMode;
        public static int Widget_Sherlock_Light_ActionMode_Inverse;
        public static int Widget_Sherlock_Light_ActivityChooserView;
        public static int Widget_Sherlock_Light_Button_Small;
        public static int Widget_Sherlock_Light_DropDownItem_Spinner;
        public static int Widget_Sherlock_Light_ListPopupWindow;
        public static int Widget_Sherlock_Light_ListView_DropDown;
        public static int Widget_Sherlock_Light_PopupMenu;
        public static int Widget_Sherlock_Light_PopupWindow_ActionMode;
        public static int Widget_Sherlock_Light_ProgressBar;
        public static int Widget_Sherlock_Light_ProgressBar_Horizontal;
        public static int Widget_Sherlock_Light_SearchAutoCompleteTextView;
        public static int Widget_Sherlock_Light_Spinner_DropDown_ActionBar;
        public static int Widget_Sherlock_ListPopupWindow;
        public static int Widget_Sherlock_ListView_DropDown;
        public static int Widget_Sherlock_PopupMenu;
        public static int Widget_Sherlock_PopupWindow_ActionMode;
        public static int Widget_Sherlock_ProgressBar;
        public static int Widget_Sherlock_ProgressBar_Horizontal;
        public static int Widget_Sherlock_SearchAutoCompleteTextView;
        public static int Widget_Sherlock_Spinner_DropDown_ActionBar;
        public static int Widget_Sherlock_TextView_SpinnerItem;

        static {
            Black = 2131492958;
            ButtonBlack = 2131492954;
            ButtonLight = 2131492953;
            ButtonOrange = 2131492955;
            ButtonPink = 2131492956;
            Light = 2131492957;
            Orange = 2131492959;
            Pink = 2131492960;
            Sherlock___TextAppearance_Small = 2131492934;
            Sherlock___Theme = 2131492945;
            Sherlock___Theme_DarkActionBar = 2131492947;
            Sherlock___Theme_Light = 2131492946;
            Sherlock___Widget_ActionBar = 2131492865;
            Sherlock___Widget_ActionMode = 2131492886;
            Sherlock___Widget_ActivityChooserView = 2131492894;
            Sherlock___Widget_Holo_DropDownItem = 2131492905;
            Sherlock___Widget_Holo_ListView = 2131492902;
            Sherlock___Widget_Holo_Spinner = 2131492899;
            Sherlock___Widget_SearchAutoCompleteTextView = 2131492915;
            TextAppearance_Sherlock = 2131492938;
            TextAppearance_Sherlock_Light_SearchResult = 2131492942;
            TextAppearance_Sherlock_Light_SearchResult_Subtitle = 2131492944;
            TextAppearance_Sherlock_Light_SearchResult_Title = 2131492943;
            TextAppearance_Sherlock_Light_Small = 2131492936;
            TextAppearance_Sherlock_Light_Widget_PopupMenu_Large = 2131492929;
            TextAppearance_Sherlock_Light_Widget_PopupMenu_Small = 2131492931;
            TextAppearance_Sherlock_SearchResult = 2131492939;
            TextAppearance_Sherlock_SearchResult_Subtitle = 2131492941;
            TextAppearance_Sherlock_SearchResult_Title = 2131492940;
            TextAppearance_Sherlock_Small = 2131492935;
            TextAppearance_Sherlock_Widget_ActionBar_Menu = 2131492918;
            TextAppearance_Sherlock_Widget_ActionBar_Subtitle = 2131492921;
            TextAppearance_Sherlock_Widget_ActionBar_Subtitle_Inverse = 2131492922;
            TextAppearance_Sherlock_Widget_ActionBar_Title = 2131492919;
            TextAppearance_Sherlock_Widget_ActionBar_Title_Inverse = 2131492920;
            TextAppearance_Sherlock_Widget_ActionMode_Subtitle = 2131492925;
            TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse = 2131492926;
            TextAppearance_Sherlock_Widget_ActionMode_Title = 2131492923;
            TextAppearance_Sherlock_Widget_ActionMode_Title_Inverse = 2131492924;
            TextAppearance_Sherlock_Widget_DropDownHint = 2131492937;
            TextAppearance_Sherlock_Widget_DropDownItem = 2131492933;
            TextAppearance_Sherlock_Widget_PopupMenu = 2131492927;
            TextAppearance_Sherlock_Widget_PopupMenu_Large = 2131492928;
            TextAppearance_Sherlock_Widget_PopupMenu_Small = 2131492930;
            TextAppearance_Sherlock_Widget_TextView_SpinnerItem = 2131492932;
            Theme_Sherlock = 2131492948;
            Theme_Sherlock_Light = 2131492949;
            Theme_Sherlock_Light_DarkActionBar = 2131492950;
            Theme_Sherlock_Light_NoActionBar = 2131492952;
            Theme_Sherlock_NoActionBar = 2131492951;
            Widget = 2131492864;
            Widget_Sherlock_ActionBar = 2131492866;
            Widget_Sherlock_ActionBar_Solid = 2131492867;
            Widget_Sherlock_ActionBar_TabBar = 2131492874;
            Widget_Sherlock_ActionBar_TabText = 2131492877;
            Widget_Sherlock_ActionBar_TabView = 2131492871;
            Widget_Sherlock_ActionButton = 2131492880;
            Widget_Sherlock_ActionButton_CloseMode = 2131492882;
            Widget_Sherlock_ActionButton_Overflow = 2131492884;
            Widget_Sherlock_ActionMode = 2131492887;
            Widget_Sherlock_ActivityChooserView = 2131492895;
            Widget_Sherlock_Button_Small = 2131492897;
            Widget_Sherlock_DropDownItem_Spinner = 2131492906;
            Widget_Sherlock_Light_ActionBar = 2131492868;
            Widget_Sherlock_Light_ActionBar_Solid = 2131492869;
            Widget_Sherlock_Light_ActionBar_Solid_Inverse = 2131492870;
            Widget_Sherlock_Light_ActionBar_TabBar = 2131492875;
            Widget_Sherlock_Light_ActionBar_TabBar_Inverse = 2131492876;
            Widget_Sherlock_Light_ActionBar_TabText = 2131492878;
            Widget_Sherlock_Light_ActionBar_TabText_Inverse = 2131492879;
            Widget_Sherlock_Light_ActionBar_TabView = 2131492872;
            Widget_Sherlock_Light_ActionBar_TabView_Inverse = 2131492873;
            Widget_Sherlock_Light_ActionButton = 2131492881;
            Widget_Sherlock_Light_ActionButton_CloseMode = 2131492883;
            Widget_Sherlock_Light_ActionButton_Overflow = 2131492885;
            Widget_Sherlock_Light_ActionMode = 2131492888;
            Widget_Sherlock_Light_ActionMode_Inverse = 2131492889;
            Widget_Sherlock_Light_ActivityChooserView = 2131492896;
            Widget_Sherlock_Light_Button_Small = 2131492898;
            Widget_Sherlock_Light_DropDownItem_Spinner = 2131492907;
            Widget_Sherlock_Light_ListPopupWindow = 2131492891;
            Widget_Sherlock_Light_ListView_DropDown = 2131492904;
            Widget_Sherlock_Light_PopupMenu = 2131492893;
            Widget_Sherlock_Light_PopupWindow_ActionMode = 2131492909;
            Widget_Sherlock_Light_ProgressBar = 2131492911;
            Widget_Sherlock_Light_ProgressBar_Horizontal = 2131492913;
            Widget_Sherlock_Light_SearchAutoCompleteTextView = 2131492917;
            Widget_Sherlock_Light_Spinner_DropDown_ActionBar = 2131492901;
            Widget_Sherlock_ListPopupWindow = 2131492890;
            Widget_Sherlock_ListView_DropDown = 2131492903;
            Widget_Sherlock_PopupMenu = 2131492892;
            Widget_Sherlock_PopupWindow_ActionMode = 2131492908;
            Widget_Sherlock_ProgressBar = 2131492910;
            Widget_Sherlock_ProgressBar_Horizontal = 2131492912;
            Widget_Sherlock_SearchAutoCompleteTextView = 2131492916;
            Widget_Sherlock_Spinner_DropDown_ActionBar = 2131492900;
            Widget_Sherlock_TextView_SpinnerItem = 2131492914;
        }
    }

    public final class styleable {
        public static final int[] SherlockActionBar;
        public static int SherlockActionBar_background;
        public static int SherlockActionBar_backgroundSplit;
        public static int SherlockActionBar_backgroundStacked;
        public static int SherlockActionBar_customNavigationLayout;
        public static int SherlockActionBar_displayOptions;
        public static int SherlockActionBar_divider;
        public static int SherlockActionBar_height;
        public static int SherlockActionBar_homeLayout;
        public static int SherlockActionBar_icon;
        public static int SherlockActionBar_indeterminateProgressStyle;
        public static int SherlockActionBar_itemPadding;
        public static int SherlockActionBar_logo;
        public static int SherlockActionBar_navigationMode;
        public static int SherlockActionBar_progressBarPadding;
        public static int SherlockActionBar_progressBarStyle;
        public static int SherlockActionBar_subtitle;
        public static int SherlockActionBar_subtitleTextStyle;
        public static int SherlockActionBar_title;
        public static int SherlockActionBar_titleTextStyle;
        public static final int[] SherlockActionMenuItemView;
        public static int SherlockActionMenuItemView_android_minWidth;
        public static final int[] SherlockActionMode;
        public static int SherlockActionMode_background;
        public static int SherlockActionMode_backgroundSplit;
        public static int SherlockActionMode_height;
        public static int SherlockActionMode_subtitleTextStyle;
        public static int SherlockActionMode_titleTextStyle;
        public static final int[] SherlockActivityChooserView;
        public static int SherlockActivityChooserView_android_background;
        public static int SherlockActivityChooserView_expandActivityOverflowButtonDrawable;
        public static int SherlockActivityChooserView_initialActivityCount;
        public static final int[] SherlockMenuGroup;
        public static int SherlockMenuGroup_android_checkableBehavior;
        public static int SherlockMenuGroup_android_enabled;
        public static int SherlockMenuGroup_android_id;
        public static int SherlockMenuGroup_android_menuCategory;
        public static int SherlockMenuGroup_android_orderInCategory;
        public static int SherlockMenuGroup_android_visible;
        public static final int[] SherlockMenuItem;
        public static int SherlockMenuItem_android_actionLayout;
        public static int SherlockMenuItem_android_actionProviderClass;
        public static int SherlockMenuItem_android_actionViewClass;
        public static int SherlockMenuItem_android_alphabeticShortcut;
        public static int SherlockMenuItem_android_checkable;
        public static int SherlockMenuItem_android_checked;
        public static int SherlockMenuItem_android_enabled;
        public static int SherlockMenuItem_android_icon;
        public static int SherlockMenuItem_android_id;
        public static int SherlockMenuItem_android_menuCategory;
        public static int SherlockMenuItem_android_numericShortcut;
        public static int SherlockMenuItem_android_onClick;
        public static int SherlockMenuItem_android_orderInCategory;
        public static int SherlockMenuItem_android_showAsAction;
        public static int SherlockMenuItem_android_title;
        public static int SherlockMenuItem_android_titleCondensed;
        public static int SherlockMenuItem_android_visible;
        public static final int[] SherlockMenuView;
        public static int SherlockMenuView_headerBackground;
        public static int SherlockMenuView_horizontalDivider;
        public static int SherlockMenuView_itemBackground;
        public static int SherlockMenuView_itemIconDisabledAlpha;
        public static int SherlockMenuView_itemTextAppearance;
        public static int SherlockMenuView_preserveIconSpacing;
        public static int SherlockMenuView_verticalDivider;
        public static int SherlockMenuView_windowAnimationStyle;
        public static final int[] SherlockSearchView;
        public static int SherlockSearchView_android_imeOptions;
        public static int SherlockSearchView_android_inputType;
        public static int SherlockSearchView_android_maxWidth;
        public static int SherlockSearchView_iconifiedByDefault;
        public static int SherlockSearchView_queryHint;
        public static final int[] SherlockSpinner;
        public static int SherlockSpinner_android_dropDownHorizontalOffset;
        public static int SherlockSpinner_android_dropDownSelector;
        public static int SherlockSpinner_android_dropDownVerticalOffset;
        public static int SherlockSpinner_android_dropDownWidth;
        public static int SherlockSpinner_android_gravity;
        public static int SherlockSpinner_android_popupBackground;
        public static int SherlockSpinner_android_popupPromptView;
        public static int SherlockSpinner_android_prompt;
        public static final int[] SherlockTheme;
        public static int SherlockTheme_actionBarDivider;
        public static int SherlockTheme_actionBarItemBackground;
        public static int SherlockTheme_actionBarSize;
        public static int SherlockTheme_actionBarSplitStyle;
        public static int SherlockTheme_actionBarStyle;
        public static int SherlockTheme_actionBarTabBarStyle;
        public static int SherlockTheme_actionBarTabStyle;
        public static int SherlockTheme_actionBarTabTextStyle;
        public static int SherlockTheme_actionBarWidgetTheme;
        public static int SherlockTheme_actionButtonStyle;
        public static int SherlockTheme_actionDropDownStyle;
        public static int SherlockTheme_actionMenuTextAppearance;
        public static int SherlockTheme_actionMenuTextColor;
        public static int SherlockTheme_actionModeBackground;
        public static int SherlockTheme_actionModeCloseButtonStyle;
        public static int SherlockTheme_actionModeCloseDrawable;
        public static int SherlockTheme_actionModePopupWindowStyle;
        public static int SherlockTheme_actionModeShareDrawable;
        public static int SherlockTheme_actionModeSplitBackground;
        public static int SherlockTheme_actionModeStyle;
        public static int SherlockTheme_actionOverflowButtonStyle;
        public static int SherlockTheme_actionSpinnerItemStyle;
        public static int SherlockTheme_activatedBackgroundIndicator;
        public static int SherlockTheme_activityChooserViewStyle;
        public static int SherlockTheme_buttonStyleSmall;
        public static int SherlockTheme_dividerVertical;
        public static int SherlockTheme_dropDownHintAppearance;
        public static int SherlockTheme_dropDownListViewStyle;
        public static int SherlockTheme_dropdownListPreferredItemHeight;
        public static int SherlockTheme_homeAsUpIndicator;
        public static int SherlockTheme_listPopupWindowStyle;
        public static int SherlockTheme_listPreferredItemHeightSmall;
        public static int SherlockTheme_listPreferredItemPaddingLeft;
        public static int SherlockTheme_listPreferredItemPaddingRight;
        public static int SherlockTheme_popupMenuStyle;
        public static int SherlockTheme_searchAutoCompleteTextView;
        public static int SherlockTheme_searchDropdownBackground;
        public static int SherlockTheme_searchResultListItemHeight;
        public static int SherlockTheme_searchViewCloseIcon;
        public static int SherlockTheme_searchViewEditQuery;
        public static int SherlockTheme_searchViewEditQueryBackground;
        public static int SherlockTheme_searchViewGoIcon;
        public static int SherlockTheme_searchViewSearchIcon;
        public static int SherlockTheme_searchViewTextField;
        public static int SherlockTheme_searchViewTextFieldRight;
        public static int SherlockTheme_searchViewVoiceIcon;
        public static int SherlockTheme_selectableItemBackground;
        public static int SherlockTheme_spinnerDropDownItemStyle;
        public static int SherlockTheme_spinnerItemStyle;
        public static int SherlockTheme_textAppearanceLargePopupMenu;
        public static int SherlockTheme_textAppearanceListItemSmall;
        public static int SherlockTheme_textAppearanceSearchResultSubtitle;
        public static int SherlockTheme_textAppearanceSearchResultTitle;
        public static int SherlockTheme_textAppearanceSmall;
        public static int SherlockTheme_textAppearanceSmallPopupMenu;
        public static int SherlockTheme_textColorPrimary;
        public static int SherlockTheme_textColorPrimaryDisableOnly;
        public static int SherlockTheme_textColorPrimaryInverse;
        public static int SherlockTheme_textColorSearchUrl;
        public static int SherlockTheme_windowActionBar;
        public static int SherlockTheme_windowActionBarOverlay;
        public static int SherlockTheme_windowActionModeOverlay;
        public static int SherlockTheme_windowContentOverlay;
        public static int SherlockTheme_windowMinWidthMajor;
        public static int SherlockTheme_windowMinWidthMinor;
        public static int SherlockTheme_windowNoTitle;
        public static int SherlockTheme_windowSplitActionBar;
        public static final int[] SherlockView;
        public static int SherlockView_android_focusable;

        static {
            SherlockActionBar = new int[]{2130771968, 2130771969, 2130771970, 2130771971, 2130771972, 2130771973, 2130772041, 2130772042, 2130772043, 2130772044, 2130772045, 2130772046, 2130772047, 2130772048, 2130772049, 2130772050, 2130772051, 2130772052, 2130772053};
            SherlockActionBar_background = 2;
            SherlockActionBar_backgroundSplit = 3;
            SherlockActionBar_backgroundStacked = 12;
            SherlockActionBar_customNavigationLayout = 13;
            SherlockActionBar_displayOptions = 7;
            SherlockActionBar_divider = 5;
            SherlockActionBar_height = 4;
            SherlockActionBar_homeLayout = 14;
            SherlockActionBar_icon = 10;
            SherlockActionBar_indeterminateProgressStyle = 16;
            SherlockActionBar_itemPadding = 18;
            SherlockActionBar_logo = 11;
            SherlockActionBar_navigationMode = 6;
            SherlockActionBar_progressBarPadding = 17;
            SherlockActionBar_progressBarStyle = 15;
            SherlockActionBar_subtitle = 9;
            SherlockActionBar_subtitleTextStyle = 1;
            SherlockActionBar_title = 8;
            SherlockActionBar_titleTextStyle = 0;
            SherlockActionMenuItemView = new int[]{16843071};
            SherlockActionMenuItemView_android_minWidth = 0;
            SherlockActionMode = new int[]{2130771968, 2130771969, 2130771970, 2130771971, 2130771972};
            SherlockActionMode_background = 2;
            SherlockActionMode_backgroundSplit = 3;
            SherlockActionMode_height = 4;
            SherlockActionMode_subtitleTextStyle = 1;
            SherlockActionMode_titleTextStyle = 0;
            SherlockActivityChooserView = new int[]{16842964, 2130772062, 2130772063};
            SherlockActivityChooserView_android_background = 0;
            SherlockActivityChooserView_expandActivityOverflowButtonDrawable = 2;
            SherlockActivityChooserView_initialActivityCount = 1;
            SherlockMenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            SherlockMenuGroup_android_checkableBehavior = 5;
            SherlockMenuGroup_android_enabled = 0;
            SherlockMenuGroup_android_id = 1;
            SherlockMenuGroup_android_menuCategory = 3;
            SherlockMenuGroup_android_orderInCategory = 4;
            SherlockMenuGroup_android_visible = 2;
            SherlockMenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, 16843481, 16843515, 16843516, 16843657};
            SherlockMenuItem_android_actionLayout = 14;
            SherlockMenuItem_android_actionProviderClass = 16;
            SherlockMenuItem_android_actionViewClass = 15;
            SherlockMenuItem_android_alphabeticShortcut = 9;
            SherlockMenuItem_android_checkable = 11;
            SherlockMenuItem_android_checked = 3;
            SherlockMenuItem_android_enabled = 1;
            SherlockMenuItem_android_icon = 0;
            SherlockMenuItem_android_id = 2;
            SherlockMenuItem_android_menuCategory = 5;
            SherlockMenuItem_android_numericShortcut = 10;
            SherlockMenuItem_android_onClick = 12;
            SherlockMenuItem_android_orderInCategory = 6;
            SherlockMenuItem_android_showAsAction = 13;
            SherlockMenuItem_android_title = 7;
            SherlockMenuItem_android_titleCondensed = 8;
            SherlockMenuItem_android_visible = 4;
            SherlockMenuView = new int[]{2130772054, 2130772055, 2130772056, 2130772057, 2130772058, 2130772059, 2130772060, 2130772061};
            SherlockMenuView_headerBackground = 3;
            SherlockMenuView_horizontalDivider = 1;
            SherlockMenuView_itemBackground = 4;
            SherlockMenuView_itemIconDisabledAlpha = 6;
            SherlockMenuView_itemTextAppearance = 0;
            SherlockMenuView_preserveIconSpacing = 7;
            SherlockMenuView_verticalDivider = 2;
            SherlockMenuView_windowAnimationStyle = 5;
            SherlockSearchView = new int[]{16843039, 16843296, 16843364, 2130772064, 2130772065};
            SherlockSearchView_android_imeOptions = 2;
            SherlockSearchView_android_inputType = 1;
            SherlockSearchView_android_maxWidth = 0;
            SherlockSearchView_iconifiedByDefault = 3;
            SherlockSearchView_queryHint = 4;
            SherlockSpinner = new int[]{16842927, 16843125, 16843126, 16843131, 16843362, 16843436, 16843437, 16843793};
            SherlockSpinner_android_dropDownHorizontalOffset = 5;
            SherlockSpinner_android_dropDownSelector = 1;
            SherlockSpinner_android_dropDownVerticalOffset = 6;
            SherlockSpinner_android_dropDownWidth = 4;
            SherlockSpinner_android_gravity = 0;
            SherlockSpinner_android_popupBackground = 2;
            SherlockSpinner_android_popupPromptView = 7;
            SherlockSpinner_android_prompt = 3;
            SherlockTheme = new int[]{2130771974, 2130771975, 2130771976, 2130771977, 2130771978, 2130771979, 2130771980, 2130771981, 2130771982, 2130771983, 2130771984, 2130771985, 2130771986, 2130771987, 2130771988, 2130771989, 2130771990, 2130771991, 2130771992, 2130771993, 2130771994, 2130771995, 2130771996, 2130771997, 2130771998, 2130771999, 2130772000, 2130772001, 2130772002, 2130772003, 2130772004, 2130772005, 2130772006, 2130772007, 2130772008, 2130772009, 2130772010, 2130772011, 2130772012, 2130772013, 2130772014, 2130772015, 2130772016, 2130772017, 2130772018, 2130772019, 2130772020, 2130772021, 2130772022, 2130772023, 2130772024, 2130772025, 2130772026, 2130772027, 2130772028, 2130772029, 2130772030, 2130772031, 2130772032, 2130772033, 2130772034, 2130772035, 2130772036, 2130772037, 2130772038, 2130772039, 2130772040};
            SherlockTheme_actionBarDivider = 8;
            SherlockTheme_actionBarItemBackground = 9;
            SherlockTheme_actionBarSize = 7;
            SherlockTheme_actionBarSplitStyle = 5;
            SherlockTheme_actionBarStyle = 4;
            SherlockTheme_actionBarTabBarStyle = 1;
            SherlockTheme_actionBarTabStyle = 0;
            SherlockTheme_actionBarTabTextStyle = 2;
            SherlockTheme_actionBarWidgetTheme = 6;
            SherlockTheme_actionButtonStyle = 52;
            SherlockTheme_actionDropDownStyle = 51;
            SherlockTheme_actionMenuTextAppearance = 10;
            SherlockTheme_actionMenuTextColor = 11;
            SherlockTheme_actionModeBackground = 14;
            SherlockTheme_actionModeCloseButtonStyle = 13;
            SherlockTheme_actionModeCloseDrawable = 16;
            SherlockTheme_actionModePopupWindowStyle = 18;
            SherlockTheme_actionModeShareDrawable = 17;
            SherlockTheme_actionModeSplitBackground = 15;
            SherlockTheme_actionModeStyle = 12;
            SherlockTheme_actionOverflowButtonStyle = 3;
            SherlockTheme_actionSpinnerItemStyle = 57;
            SherlockTheme_activatedBackgroundIndicator = 65;
            SherlockTheme_activityChooserViewStyle = 64;
            SherlockTheme_buttonStyleSmall = 19;
            SherlockTheme_dividerVertical = 50;
            SherlockTheme_dropDownHintAppearance = 66;
            SherlockTheme_dropDownListViewStyle = 54;
            SherlockTheme_dropdownListPreferredItemHeight = 56;
            SherlockTheme_homeAsUpIndicator = 53;
            SherlockTheme_listPopupWindowStyle = 63;
            SherlockTheme_listPreferredItemHeightSmall = 44;
            SherlockTheme_listPreferredItemPaddingLeft = 45;
            SherlockTheme_listPreferredItemPaddingRight = 46;
            SherlockTheme_popupMenuStyle = 55;
            SherlockTheme_searchAutoCompleteTextView = 30;
            SherlockTheme_searchDropdownBackground = 31;
            SherlockTheme_searchResultListItemHeight = 41;
            SherlockTheme_searchViewCloseIcon = 32;
            SherlockTheme_searchViewEditQuery = 36;
            SherlockTheme_searchViewEditQueryBackground = 37;
            SherlockTheme_searchViewGoIcon = 33;
            SherlockTheme_searchViewSearchIcon = 34;
            SherlockTheme_searchViewTextField = 38;
            SherlockTheme_searchViewTextFieldRight = 39;
            SherlockTheme_searchViewVoiceIcon = 35;
            SherlockTheme_selectableItemBackground = 20;
            SherlockTheme_spinnerDropDownItemStyle = 29;
            SherlockTheme_spinnerItemStyle = 28;
            SherlockTheme_textAppearanceLargePopupMenu = 22;
            SherlockTheme_textAppearanceListItemSmall = 47;
            SherlockTheme_textAppearanceSearchResultSubtitle = 43;
            SherlockTheme_textAppearanceSearchResultTitle = 42;
            SherlockTheme_textAppearanceSmall = 24;
            SherlockTheme_textAppearanceSmallPopupMenu = 23;
            SherlockTheme_textColorPrimary = 25;
            SherlockTheme_textColorPrimaryDisableOnly = 26;
            SherlockTheme_textColorPrimaryInverse = 27;
            SherlockTheme_textColorSearchUrl = 40;
            SherlockTheme_windowActionBar = 59;
            SherlockTheme_windowActionBarOverlay = 60;
            SherlockTheme_windowActionModeOverlay = 61;
            SherlockTheme_windowContentOverlay = 21;
            SherlockTheme_windowMinWidthMajor = 48;
            SherlockTheme_windowMinWidthMinor = 49;
            SherlockTheme_windowNoTitle = 58;
            SherlockTheme_windowSplitActionBar = 62;
            SherlockView = new int[]{16842970};
            SherlockView_android_focusable = 0;
        }
    }

    public final class xml {
        public static int preferences;

        static {
            preferences = 2131034112;
        }
    }
}