import com.google.gson.InstanceCreator;
import java.lang.reflect.Type;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.URI;
import java.net.URL;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Collection;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.SortedSet;
import java.util.UUID;

final class ab
{
  private static final ab.p A;
  private static final bk B;
  private static final bk C;
  private static final bk D;
  private static final ab.g a;
  private static final ab.h b;
  private static final ab.i c;
  private static final ab.j d;
  private static final ab.m e;
  private static final ab.ac f;
  private static final ab.ab g;
  private static final ab.ad h;
  private static final ab.s i;
  private static final ab.f j;
  private static final ab.v k;
  private static final ab.a l;
  private static final ab.b m;
  private static final ab.c n;
  private static final ab.d o;
  private static final ab.e p;
  private static final ab.k q;
  private static final ab.n r;
  private static final ab.r s;
  private static final ab.t t;
  private static final ab.w u;
  private static final ab.y v;
  private static final ab.z w;
  private static final ab.x x;
  private static final ab.aa y;
  private static final ab.q z;
  
  static
  {
    Object localObject1 = new ab$g;
    ((ab.g)localObject1).<init>();
    a = (ab.g)localObject1;
    localObject1 = new ab$h;
    ((ab.h)localObject1).<init>();
    b = (ab.h)localObject1;
    localObject1 = new ab$i;
    ((ab.i)localObject1).<init>();
    c = (ab.i)localObject1;
    localObject1 = new ab$j;
    ((ab.j)localObject1).<init>();
    d = (ab.j)localObject1;
    localObject1 = new ab$m;
    ((ab.m)localObject1).<init>();
    e = (ab.m)localObject1;
    localObject1 = new ab$ac;
    ((ab.ac)localObject1).<init>();
    f = (ab.ac)localObject1;
    localObject1 = new ab$ab;
    ((ab.ab)localObject1).<init>();
    g = (ab.ab)localObject1;
    localObject1 = new ab$ad;
    ((ab.ad)localObject1).<init>();
    h = (ab.ad)localObject1;
    localObject1 = new ab$s;
    ((ab.s)localObject1).<init>();
    i = (ab.s)localObject1;
    localObject1 = new ab$f;
    ((ab.f)localObject1).<init>();
    j = (ab.f)localObject1;
    localObject1 = new ab$v;
    ((ab.v)localObject1).<init>();
    k = (ab.v)localObject1;
    localObject1 = new ab$a;
    ((ab.a)localObject1).<init>();
    l = (ab.a)localObject1;
    localObject1 = new ab$b;
    ((ab.b)localObject1).<init>();
    m = (ab.b)localObject1;
    localObject1 = new ab$c;
    ((ab.c)localObject1).<init>();
    n = (ab.c)localObject1;
    localObject1 = new ab$d;
    ((ab.d)localObject1).<init>();
    o = (ab.d)localObject1;
    localObject1 = new ab$e;
    ((ab.e)localObject1).<init>();
    p = (ab.e)localObject1;
    localObject1 = new ab$k;
    ((ab.k)localObject1).<init>();
    q = (ab.k)localObject1;
    localObject1 = new ab$n;
    ((ab.n)localObject1).<init>();
    r = (ab.n)localObject1;
    localObject1 = new ab$r;
    ((ab.r)localObject1).<init>();
    s = (ab.r)localObject1;
    localObject1 = new ab$t;
    ((ab.t)localObject1).<init>();
    t = (ab.t)localObject1;
    localObject1 = new ab$w;
    ((ab.w)localObject1).<init>();
    u = (ab.w)localObject1;
    localObject1 = new ab$y;
    ((ab.y)localObject1).<init>();
    v = (ab.y)localObject1;
    localObject1 = new ab$z;
    ((ab.z)localObject1).<init>();
    w = (ab.z)localObject1;
    localObject1 = new ab$x;
    ((ab.x)localObject1).<init>();
    x = (ab.x)localObject1;
    localObject1 = new ab$aa;
    ((ab.aa)localObject1).<init>();
    y = (ab.aa)localObject1;
    localObject1 = new ab$q;
    ((ab.q)localObject1).<init>();
    z = (ab.q)localObject1;
    localObject1 = new ab$p;
    ((ab.p)localObject1).<init>();
    A = (ab.p)localObject1;
    localObject1 = new bk;
    ((bk)localObject1).<init>();
    Class localClass = Enum.class;
    Object localObject2 = e;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = URL.class;
    localObject2 = f;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = URI.class;
    localObject2 = g;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = UUID.class;
    localObject2 = h;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Locale.class;
    localObject2 = i;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Collection.class;
    localObject2 = j;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Map.class;
    localObject2 = k;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = java.util.Date.class;
    localObject2 = a;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = java.sql.Date.class;
    localObject2 = b;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Timestamp.class;
    localObject2 = a;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Time.class;
    localObject2 = c;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Calendar.class;
    localObject2 = A;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = GregorianCalendar.class;
    localObject2 = A;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = BigDecimal.class;
    localObject2 = l;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = BigInteger.class;
    localObject2 = m;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Boolean.class;
    localObject2 = n;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Boolean.TYPE;
    localObject2 = n;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Byte.class;
    localObject2 = o;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Byte.TYPE;
    localObject2 = o;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Character.class;
    localObject2 = p;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Character.TYPE;
    localObject2 = p;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Integer.class;
    localObject2 = s;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Integer.TYPE;
    localObject2 = s;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Number.class;
    localObject2 = u;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Short.class;
    localObject2 = v;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Short.TYPE;
    localObject2 = v;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = String.class;
    localObject2 = w;
    ((bk)localObject1).a(localClass, localObject2);
    ((bk)localObject1).a();
    B = (bk)localObject1;
    localObject1 = new bk;
    ((bk)localObject1).<init>();
    localClass = Enum.class;
    localObject2 = e;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = URL.class;
    localObject2 = f;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = URI.class;
    localObject2 = g;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = UUID.class;
    localObject2 = h;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Locale.class;
    localObject2 = i;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Collection.class;
    localObject2 = j;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Map.class;
    localObject2 = k;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = java.util.Date.class;
    localObject2 = a;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = java.sql.Date.class;
    localObject2 = b;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Timestamp.class;
    localObject2 = d;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Time.class;
    localObject2 = c;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Calendar.class;
    localObject2 = A;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = GregorianCalendar.class;
    localObject2 = A;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = BigDecimal.class;
    localObject2 = l;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = BigInteger.class;
    localObject2 = m;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Boolean.class;
    localObject2 = n;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Boolean.TYPE;
    localObject2 = n;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Byte.class;
    localObject2 = o;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Byte.TYPE;
    localObject2 = o;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Character.class;
    localObject2 = p;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Character.TYPE;
    localObject2 = p;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Double.class;
    localObject2 = q;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Double.TYPE;
    localObject2 = q;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Float.class;
    localObject2 = r;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Float.TYPE;
    localObject2 = r;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Integer.class;
    localObject2 = s;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Integer.TYPE;
    localObject2 = s;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Long.class;
    localObject2 = t;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Long.TYPE;
    localObject2 = t;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Number.class;
    localObject2 = u;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Short.class;
    localObject2 = v;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Short.TYPE;
    localObject2 = v;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    localClass = String.class;
    localObject2 = w;
    localObject2 = a((am)localObject2);
    ((bk)localObject1).a(localClass, localObject2);
    ((bk)localObject1).a();
    C = (bk)localObject1;
    localObject1 = new bk;
    ((bk)localObject1).<init>();
    localClass = Map.class;
    localObject2 = k;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Collection.class;
    localObject2 = j;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Set.class;
    localObject2 = z;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = SortedSet.class;
    localObject2 = y;
    ((bk)localObject1).a(localClass, localObject2);
    localClass = Properties.class;
    localObject2 = x;
    ((bk)localObject1).a(localClass, localObject2);
    ((bk)localObject1).a();
    D = (bk)localObject1;
  }
  
  private static am<?> a(am<?> paramam)
  {
    an localan = new an;
    localan.<init>(paramam);
    return localan;
  }
  
  static bk<ay<?>> a()
  {
    Object localObject1 = ba.a;
    bk localbk = new bk;
    localbk.<init>();
    Object localObject2 = new ab$l;
    ((ab.l)localObject2).<init>();
    Class localClass = Double.class;
    localbk.b(localClass, localObject2);
    localClass = Double.TYPE;
    localbk.b(localClass, localObject2);
    localObject2 = new ab$o;
    ((ab.o)localObject2).<init>();
    localClass = Float.class;
    localbk.b(localClass, localObject2);
    localClass = Float.TYPE;
    localbk.b(localClass, localObject2);
    localObject2 = new ab$u;
    ((ab.u)localObject2).<init>((ba)localObject1);
    localObject1 = Long.class;
    localbk.b((Type)localObject1, localObject2);
    localObject1 = Long.TYPE;
    localbk.b((Type)localObject1, localObject2);
    localObject1 = B;
    localbk.a((bk)localObject1);
    return localbk;
  }
  
  static bk<am<?>> b()
  {
    bk localbk = C;
    return localbk;
  }
  
  static bk<InstanceCreator<?>> c()
  {
    bk localbk = D;
    return localbk;
  }
}

/* Location:
 * Qualified Name:     ab
 * Java Class Version: 5 (49.0)
 * JD-Core Version:    0.7.1
 */