package org.kxml2.wap.syncml;

import org.kxml2.wap.WbxmlParser;
import org.kxml2.wap.WbxmlSerializer;

public abstract class SyncML
{
  public static final String[] TAG_TABLE_0;
  public static final String[] TAG_TABLE_1;
  public static final String[] TAG_TABLE_2_DM;
  
  static
  {
    int i6 = 4;
    int i5 = 3;
    int i4 = 2;
    int i3 = 1;
    int i2 = 0;
    int i = 56;
    String[] arrayOfString1 = new String[i];
    String str1 = "Add";
    arrayOfString1[i2] = str1;
    str1 = "Alert";
    arrayOfString1[i3] = str1;
    str1 = "Archive";
    arrayOfString1[i4] = str1;
    str1 = "Atomic";
    arrayOfString1[i5] = str1;
    str1 = "Chal";
    arrayOfString1[i6] = str1;
    int m = 5;
    String str4 = "Cmd";
    arrayOfString1[m] = str4;
    m = 6;
    str4 = "CmdID";
    arrayOfString1[m] = str4;
    m = 7;
    str4 = "CmdRef";
    arrayOfString1[m] = str4;
    m = 8;
    str4 = "Copy";
    arrayOfString1[m] = str4;
    m = 9;
    str4 = "Cred";
    arrayOfString1[m] = str4;
    m = 10;
    str4 = "Data";
    arrayOfString1[m] = str4;
    m = 11;
    str4 = "Delete";
    arrayOfString1[m] = str4;
    m = 12;
    str4 = "Exec";
    arrayOfString1[m] = str4;
    m = 13;
    str4 = "Final";
    arrayOfString1[m] = str4;
    m = 14;
    str4 = "Get";
    arrayOfString1[m] = str4;
    m = 15;
    str4 = "Item";
    arrayOfString1[m] = str4;
    m = 16;
    str4 = "Lang";
    arrayOfString1[m] = str4;
    m = 17;
    str4 = "LocName";
    arrayOfString1[m] = str4;
    m = 18;
    str4 = "LocURI";
    arrayOfString1[m] = str4;
    m = 19;
    str4 = "Map";
    arrayOfString1[m] = str4;
    m = 20;
    str4 = "MapItem";
    arrayOfString1[m] = str4;
    m = 21;
    str4 = "Meta";
    arrayOfString1[m] = str4;
    m = 22;
    str4 = "MsgID";
    arrayOfString1[m] = str4;
    m = 23;
    str4 = "MsgRef";
    arrayOfString1[m] = str4;
    m = 24;
    str4 = "NoResp";
    arrayOfString1[m] = str4;
    m = 25;
    str4 = "NoResults";
    arrayOfString1[m] = str4;
    m = 26;
    str4 = "Put";
    arrayOfString1[m] = str4;
    m = 27;
    str4 = "Replace";
    arrayOfString1[m] = str4;
    m = 28;
    str4 = "RespURI";
    arrayOfString1[m] = str4;
    m = 29;
    str4 = "Results";
    arrayOfString1[m] = str4;
    m = 30;
    str4 = "Search";
    arrayOfString1[m] = str4;
    m = 31;
    str4 = "Sequence";
    arrayOfString1[m] = str4;
    m = 32;
    str4 = "SessionID";
    arrayOfString1[m] = str4;
    m = 33;
    str4 = "SftDel";
    arrayOfString1[m] = str4;
    m = 34;
    str4 = "Source";
    arrayOfString1[m] = str4;
    m = 35;
    str4 = "SourceRef";
    arrayOfString1[m] = str4;
    m = 36;
    str4 = "Status";
    arrayOfString1[m] = str4;
    m = 37;
    str4 = "Sync";
    arrayOfString1[m] = str4;
    m = 38;
    str4 = "SyncBody";
    arrayOfString1[m] = str4;
    m = 39;
    str4 = "SyncHdr";
    arrayOfString1[m] = str4;
    m = 40;
    str4 = "SyncML";
    arrayOfString1[m] = str4;
    m = 41;
    str4 = "Target";
    arrayOfString1[m] = str4;
    m = 42;
    str4 = "TargetRef";
    arrayOfString1[m] = str4;
    m = 43;
    str4 = "Reserved for future use";
    arrayOfString1[m] = str4;
    m = 44;
    str4 = "VerDTD";
    arrayOfString1[m] = str4;
    m = 45;
    str4 = "VerProto";
    arrayOfString1[m] = str4;
    m = 46;
    str4 = "NumberOfChanged";
    arrayOfString1[m] = str4;
    m = 47;
    str4 = "MoreData";
    arrayOfString1[m] = str4;
    m = 48;
    str4 = "Field";
    arrayOfString1[m] = str4;
    m = 49;
    str4 = "Filter";
    arrayOfString1[m] = str4;
    m = 50;
    str4 = "Record";
    arrayOfString1[m] = str4;
    m = 51;
    str4 = "FilterType";
    arrayOfString1[m] = str4;
    m = 52;
    str4 = "SourceParent";
    arrayOfString1[m] = str4;
    m = 53;
    str4 = "TargetParent";
    arrayOfString1[m] = str4;
    m = 54;
    str4 = "Move";
    arrayOfString1[m] = str4;
    m = 55;
    str4 = "Correlator";
    arrayOfString1[m] = str4;
    TAG_TABLE_0 = arrayOfString1;
    int j = 18;
    String[] arrayOfString2 = new String[j];
    String str2 = "Anchor";
    arrayOfString2[i2] = str2;
    str2 = "EMI";
    arrayOfString2[i3] = str2;
    str2 = "Format";
    arrayOfString2[i4] = str2;
    str2 = "FreeID";
    arrayOfString2[i5] = str2;
    str2 = "FreeMem";
    arrayOfString2[i6] = str2;
    int n = 5;
    str4 = "Last";
    arrayOfString2[n] = str4;
    n = 6;
    str4 = "Mark";
    arrayOfString2[n] = str4;
    n = 7;
    str4 = "MaxMsgSize";
    arrayOfString2[n] = str4;
    n = 8;
    str4 = "Mem";
    arrayOfString2[n] = str4;
    n = 9;
    str4 = "MetInf";
    arrayOfString2[n] = str4;
    n = 10;
    str4 = "Next";
    arrayOfString2[n] = str4;
    n = 11;
    str4 = "NextNonce";
    arrayOfString2[n] = str4;
    n = 12;
    str4 = "SharedMem";
    arrayOfString2[n] = str4;
    n = 13;
    str4 = "Size";
    arrayOfString2[n] = str4;
    n = 14;
    str4 = "Type";
    arrayOfString2[n] = str4;
    n = 15;
    str4 = "Version";
    arrayOfString2[n] = str4;
    n = 16;
    str4 = "MaxObjSize";
    arrayOfString2[n] = str4;
    n = 17;
    str4 = "FieldLevel";
    arrayOfString2[n] = str4;
    TAG_TABLE_1 = arrayOfString2;
    int k = 56;
    String[] arrayOfString3 = new String[k];
    String str3 = "AccessType";
    arrayOfString3[i2] = str3;
    str3 = "ACL";
    arrayOfString3[i3] = str3;
    str3 = "Add";
    arrayOfString3[i4] = str3;
    str3 = "b64";
    arrayOfString3[i5] = str3;
    str3 = "bin";
    arrayOfString3[i6] = str3;
    int i1 = 5;
    str4 = "bool";
    arrayOfString3[i1] = str4;
    i1 = 6;
    str4 = "chr";
    arrayOfString3[i1] = str4;
    i1 = 7;
    str4 = "CaseSense";
    arrayOfString3[i1] = str4;
    i1 = 8;
    str4 = "CIS";
    arrayOfString3[i1] = str4;
    i1 = 9;
    str4 = "Copy";
    arrayOfString3[i1] = str4;
    i1 = 10;
    str4 = "CS";
    arrayOfString3[i1] = str4;
    i1 = 11;
    str4 = "date";
    arrayOfString3[i1] = str4;
    i1 = 12;
    str4 = "DDFName";
    arrayOfString3[i1] = str4;
    i1 = 13;
    str4 = "DefaultValue";
    arrayOfString3[i1] = str4;
    i1 = 14;
    str4 = "Delete";
    arrayOfString3[i1] = str4;
    i1 = 15;
    str4 = "Description";
    arrayOfString3[i1] = str4;
    i1 = 16;
    str4 = "DDFFormat";
    arrayOfString3[i1] = str4;
    i1 = 17;
    str4 = "DFProperties";
    arrayOfString3[i1] = str4;
    i1 = 18;
    str4 = "DFTitle";
    arrayOfString3[i1] = str4;
    i1 = 19;
    str4 = "DFType";
    arrayOfString3[i1] = str4;
    i1 = 20;
    str4 = "Dynamic";
    arrayOfString3[i1] = str4;
    i1 = 21;
    str4 = "Exec";
    arrayOfString3[i1] = str4;
    i1 = 22;
    str4 = "float";
    arrayOfString3[i1] = str4;
    i1 = 23;
    str4 = "Format";
    arrayOfString3[i1] = str4;
    i1 = 24;
    str4 = "Get";
    arrayOfString3[i1] = str4;
    i1 = 25;
    str4 = "int";
    arrayOfString3[i1] = str4;
    i1 = 26;
    str4 = "Man";
    arrayOfString3[i1] = str4;
    i1 = 27;
    str4 = "MgmtTree";
    arrayOfString3[i1] = str4;
    i1 = 28;
    str4 = "MIME";
    arrayOfString3[i1] = str4;
    i1 = 29;
    str4 = "Mod";
    arrayOfString3[i1] = str4;
    i1 = 30;
    str4 = "Name";
    arrayOfString3[i1] = str4;
    i1 = 31;
    str4 = "Node";
    arrayOfString3[i1] = str4;
    i1 = 32;
    str4 = "node";
    arrayOfString3[i1] = str4;
    i1 = 33;
    str4 = "NodeName";
    arrayOfString3[i1] = str4;
    i1 = 34;
    str4 = "null";
    arrayOfString3[i1] = str4;
    i1 = 35;
    str4 = "Occurence";
    arrayOfString3[i1] = str4;
    i1 = 36;
    str4 = "One";
    arrayOfString3[i1] = str4;
    i1 = 37;
    str4 = "OneOrMore";
    arrayOfString3[i1] = str4;
    i1 = 38;
    str4 = "OneOrN";
    arrayOfString3[i1] = str4;
    i1 = 39;
    str4 = "Path";
    arrayOfString3[i1] = str4;
    i1 = 40;
    str4 = "Permanent";
    arrayOfString3[i1] = str4;
    i1 = 41;
    str4 = "Replace";
    arrayOfString3[i1] = str4;
    i1 = 42;
    str4 = "RTProperties";
    arrayOfString3[i1] = str4;
    i1 = 43;
    str4 = "Scope";
    arrayOfString3[i1] = str4;
    i1 = 44;
    str4 = "Size";
    arrayOfString3[i1] = str4;
    i1 = 45;
    str4 = "time";
    arrayOfString3[i1] = str4;
    i1 = 46;
    str4 = "Title";
    arrayOfString3[i1] = str4;
    i1 = 47;
    str4 = "TStamp";
    arrayOfString3[i1] = str4;
    i1 = 48;
    str4 = "Type";
    arrayOfString3[i1] = str4;
    i1 = 49;
    str4 = "Value";
    arrayOfString3[i1] = str4;
    i1 = 50;
    str4 = "VerDTD";
    arrayOfString3[i1] = str4;
    i1 = 51;
    str4 = "VerNo";
    arrayOfString3[i1] = str4;
    i1 = 52;
    str4 = "xml";
    arrayOfString3[i1] = str4;
    i1 = 53;
    str4 = "ZeroOrMore";
    arrayOfString3[i1] = str4;
    i1 = 54;
    str4 = "ZeroOrN";
    arrayOfString3[i1] = str4;
    i1 = 55;
    str4 = "ZeroOrOne";
    arrayOfString3[i1] = str4;
    TAG_TABLE_2_DM = arrayOfString3;
  }
  
  public static WbxmlParser createDMParser()
  {
    WbxmlParser localWbxmlParser = createParser();
    int i = 2;
    String[] arrayOfString = TAG_TABLE_2_DM;
    localWbxmlParser.setTagTable(i, arrayOfString);
    return localWbxmlParser;
  }
  
  public static WbxmlSerializer createDMSerializer()
  {
    WbxmlSerializer localWbxmlSerializer = createSerializer();
    int i = 2;
    String[] arrayOfString = TAG_TABLE_2_DM;
    localWbxmlSerializer.setTagTable(i, arrayOfString);
    return localWbxmlSerializer;
  }
  
  public static WbxmlParser createParser()
  {
    WbxmlParser localWbxmlParser = new org/kxml2/wap/WbxmlParser;
    localWbxmlParser.<init>();
    int i = 0;
    String[] arrayOfString = TAG_TABLE_0;
    localWbxmlParser.setTagTable(i, arrayOfString);
    i = 1;
    arrayOfString = TAG_TABLE_1;
    localWbxmlParser.setTagTable(i, arrayOfString);
    return localWbxmlParser;
  }
  
  public static WbxmlSerializer createSerializer()
  {
    WbxmlSerializer localWbxmlSerializer = new org/kxml2/wap/WbxmlSerializer;
    localWbxmlSerializer.<init>();
    int i = 0;
    String[] arrayOfString = TAG_TABLE_0;
    localWbxmlSerializer.setTagTable(i, arrayOfString);
    i = 1;
    arrayOfString = TAG_TABLE_1;
    localWbxmlSerializer.setTagTable(i, arrayOfString);
    return localWbxmlSerializer;
  }
}

/* Location:
 * Qualified Name:     org.kxml2.wap.syncml.SyncML
 * Java Class Version: 1.2 (46.0)
 * JD-Core Version:    0.7.1
 */