package kagegames.apps.DWBeta;

import android.content.Context;
import android.content.res.AssetManager;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Paint.Align;
import android.graphics.Typeface;
import android.util.AttributeSet;
import android.util.DisplayMetrics;
import android.view.MotionEvent;
import android.view.View;

public class StatusBarView
  extends View
{
  private static final int PADDING_NO_SCALE = 4;
  private final int PADDING;
  private final int TAGS_PADDING_X;
  private final int TAGS_PADDING_Y;
  private final int TRANSPARENT_GAP;
  private int collarResourceID;
  private int dogResourceID;
  private Canvas mCanvas;
  private int mCanvasHalfHeight;
  private int mCanvasHalfWidth;
  private int mCanvasHeight;
  private int mCanvasWidth;
  private Bitmap mImgAggrIcon;
  private Bitmap mImgBackground;
  private Bitmap mImgCashIcon;
  private Bitmap mImgCollarScaled;
  private Bitmap mImgCredIcon;
  private Bitmap mImgDogScaled;
  private Bitmap mImgExpIcon;
  private Bitmap mImgFoodMeter;
  private Bitmap mImgHealthIcon;
  private Bitmap mImgOwnerScaled;
  private Bitmap mImgStrengthIcon;
  private Bitmap mImgTagsScaled;
  private Bitmap mImgWaterMeter;
  private Paint mPaintMeterText;
  private Paint mPaintSubText;
  private float mScaleHeight;
  private float mScaleWidth;
  private Bitmap mWinLossIcon;
  private int ownerResourceID;
  private final float scale;
  private int tagsResourceID;
  
  public StatusBarView(Context paramContext, AttributeSet paramAttributeSet)
  {
    super(paramContext, paramAttributeSet);
    mCanvasWidth = i;
    mCanvasHeight = i;
    mCanvasHalfWidth = i;
    mCanvasHalfHeight = i;
    Object localObject1 = DWApplication.getAppResources();
    localObject1 = ((Resources)localObject1).getDisplayMetrics();
    float f1 = density;
    scale = f1;
    f1 = 32.0F;
    float f5 = scale;
    f1 *= f5;
    int j = (int)f1;
    TAGS_PADDING_Y = j;
    float f2 = 0.0F;
    f5 = scale;
    f2 *= f5;
    int k = (int)f2;
    TAGS_PADDING_X = k;
    float f3 = 12.0F;
    f5 = scale;
    f3 *= f5;
    int m = (int)f3;
    TRANSPARENT_GAP = m;
    Object localObject2 = getResources();
    int i5 = 2130837597;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgBackground = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837525;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgCashIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837537;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgExpIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837526;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgCredIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837619;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mWinLossIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837538;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgFoodMeter = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837618;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgWaterMeter = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837542;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgHealthIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837599;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgStrengthIcon = ((Bitmap)localObject2);
    localObject2 = getResources();
    i5 = 2130837504;
    localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
    mImgAggrIcon = ((Bitmap)localObject2);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurOwner();
    int n = ((DWOwner)localObject2).getIconResourceID();
    ownerResourceID = n;
    Object localObject3 = getResources();
    i5 = ownerResourceID;
    localObject3 = BitmapFactory.decodeResource((Resources)localObject3, i5);
    mImgOwnerScaled = ((Bitmap)localObject3);
    localObject3 = DWApplication.getInstance();
    localObject3 = ((DWApplication)localObject3).getDWGameState();
    localObject3 = ((DWGameState)localObject3).getCurDog();
    int i1 = ((DWDog)localObject3).getIconResourceID();
    dogResourceID = i1;
    Object localObject4 = getResources();
    i5 = dogResourceID;
    localObject4 = BitmapFactory.decodeResource((Resources)localObject4, i5);
    mImgDogScaled = ((Bitmap)localObject4);
    localObject4 = getResources();
    Object localObject8 = DWApplication.getInstance();
    localObject8 = ((DWApplication)localObject8).getDWGameState();
    localObject8 = ((DWGameState)localObject8).getCurDog();
    int i6 = ((DWDog)localObject8).getIconResourceID();
    localObject4 = BitmapFactory.decodeResource((Resources)localObject4, i6);
    mImgDogScaled = ((Bitmap)localObject4);
    localObject4 = DWApplication.getInstance();
    localObject4 = ((DWApplication)localObject4).getDWGameState();
    localObject4 = ((DWGameState)localObject4).getCurOwner();
    int i2 = ((DWOwner)localObject4).getTagsResourceID();
    tagsResourceID = i2;
    Object localObject5 = getResources();
    i6 = tagsResourceID;
    localObject5 = BitmapFactory.decodeResource((Resources)localObject5, i6);
    mImgTagsScaled = ((Bitmap)localObject5);
    localObject5 = DWApplication.getInstance();
    localObject5 = ((DWApplication)localObject5).getDWGameState();
    localObject5 = ((DWGameState)localObject5).getCurOwner();
    int i3 = ((DWOwner)localObject5).getCollarResourceID();
    collarResourceID = i3;
    Object localObject6 = getResources();
    i6 = collarResourceID;
    localObject6 = BitmapFactory.decodeResource((Resources)localObject6, i6);
    mImgCollarScaled = ((Bitmap)localObject6);
    float f4 = 4.0F;
    float f6 = scale;
    f4 *= f6;
    int i4 = (int)f4;
    PADDING = i4;
    Object localObject7 = new android/graphics/Paint;
    ((Paint)localObject7).<init>();
    mPaintSubText = ((Paint)localObject7);
    localObject7 = getContext();
    localObject7 = ((Context)localObject7).getAssets();
    String str = "bohemian_typewriter.ttf";
    Typeface localTypeface = Typeface.createFromAsset((AssetManager)localObject7, str);
    localObject7 = mPaintSubText;
    ((Paint)localObject7).setTypeface(localTypeface);
    localObject7 = mPaintSubText;
    boolean bool = true;
    ((Paint)localObject7).setAntiAlias(bool);
    localObject7 = mPaintSubText;
    Paint.Align localAlign = Paint.Align.LEFT;
    ((Paint)localObject7).setTextAlign(localAlign);
    localObject7 = mPaintSubText;
    int i7 = -1;
    ((Paint)localObject7).setColor(i7);
    localObject7 = mPaintSubText;
    float f7 = 15.0F;
    float f8 = scale;
    f7 *= f8;
    ((Paint)localObject7).setTextSize(f7);
    localObject7 = new android/graphics/Paint;
    Paint localPaint = mPaintSubText;
    ((Paint)localObject7).<init>(localPaint);
    mPaintMeterText = ((Paint)localObject7);
    localObject7 = mPaintMeterText;
    int i8 = -16777216;
    ((Paint)localObject7).setColor(i8);
  }
  
  void RefreshBitmaps()
  {
    int i = 0;
    int j = ownerResourceID;
    Object localObject9 = DWApplication.getInstance();
    localObject9 = ((DWApplication)localObject9).getDWGameState();
    localObject9 = ((DWGameState)localObject9).getCurOwner();
    int i5 = ((DWOwner)localObject9).getIconResourceID();
    if (j != i5)
    {
      Object localObject1 = DWApplication.getInstance();
      localObject1 = ((DWApplication)localObject1).getDWGameState();
      localObject1 = ((DWGameState)localObject1).getCurOwner();
      int k = ((DWOwner)localObject1).getIconResourceID();
      ownerResourceID = k;
      Object localObject2 = getResources();
      i5 = ownerResourceID;
      localObject2 = BitmapFactory.decodeResource((Resources)localObject2, i5);
      mImgOwnerScaled = ((Bitmap)localObject2);
      i = 1;
    }
    int m = dogResourceID;
    Object localObject10 = DWApplication.getInstance();
    localObject10 = ((DWApplication)localObject10).getDWGameState();
    localObject10 = ((DWGameState)localObject10).getCurDog();
    int i6 = ((DWDog)localObject10).getIconResourceID();
    if (m != i6)
    {
      Object localObject3 = DWApplication.getInstance();
      localObject3 = ((DWApplication)localObject3).getDWGameState();
      localObject3 = ((DWGameState)localObject3).getCurDog();
      int n = ((DWDog)localObject3).getIconResourceID();
      dogResourceID = n;
      Object localObject4 = getResources();
      i6 = dogResourceID;
      localObject4 = BitmapFactory.decodeResource((Resources)localObject4, i6);
      mImgDogScaled = ((Bitmap)localObject4);
      i = 1;
    }
    int i1 = tagsResourceID;
    Object localObject11 = DWApplication.getInstance();
    localObject11 = ((DWApplication)localObject11).getDWGameState();
    localObject11 = ((DWGameState)localObject11).getCurOwner();
    int i7 = ((DWOwner)localObject11).getTagsResourceID();
    if (i1 != i7)
    {
      Object localObject5 = DWApplication.getInstance();
      localObject5 = ((DWApplication)localObject5).getDWGameState();
      localObject5 = ((DWGameState)localObject5).getCurOwner();
      int i2 = ((DWOwner)localObject5).getTagsResourceID();
      tagsResourceID = i2;
      Object localObject6 = getResources();
      i7 = tagsResourceID;
      localObject6 = BitmapFactory.decodeResource((Resources)localObject6, i7);
      mImgTagsScaled = ((Bitmap)localObject6);
      i = 1;
    }
    int i3 = collarResourceID;
    Object localObject12 = DWApplication.getInstance();
    localObject12 = ((DWApplication)localObject12).getDWGameState();
    localObject12 = ((DWGameState)localObject12).getCurOwner();
    int i8 = ((DWOwner)localObject12).getCollarResourceID();
    if (i3 != i8)
    {
      Object localObject7 = DWApplication.getInstance();
      localObject7 = ((DWApplication)localObject7).getDWGameState();
      localObject7 = ((DWGameState)localObject7).getCurOwner();
      int i4 = ((DWOwner)localObject7).getCollarResourceID();
      collarResourceID = i4;
      Object localObject8 = getResources();
      i8 = collarResourceID;
      localObject8 = BitmapFactory.decodeResource((Resources)localObject8, i8);
      mImgCollarScaled = ((Bitmap)localObject8);
      i = 1;
    }
    if (i != 0) {
      ScaleBitmapsToScreen();
    }
  }
  
  void ScaleBitmapsToScreen()
  {
    Bitmap localBitmap1 = mImgBackground;
    int i2 = localBitmap1.getWidth();
    localBitmap1 = mImgBackground;
    int i3 = localBitmap1.getHeight();
    int i = mCanvasWidth;
    float f1 = i;
    float f4 = i2;
    float f8 = f1 / f4;
    int j = mCanvasHeight;
    float f2 = j;
    f4 = i3;
    float f7 = f2 / f4;
    Matrix localMatrix1 = new android/graphics/Matrix;
    localMatrix1.<init>();
    localMatrix1.postScale(f7, f7);
    Bitmap localBitmap2 = mImgBackground;
    int m = 0;
    int i1 = 0;
    boolean bool1 = true;
    localBitmap2 = Bitmap.createBitmap(localBitmap2, m, i1, i2, i3, localMatrix1, bool1);
    mImgBackground = localBitmap2;
    localBitmap2 = mImgOwnerScaled;
    i2 = localBitmap2.getWidth();
    localBitmap2 = mImgOwnerScaled;
    i3 = localBitmap2.getHeight();
    int k = mCanvasHeight;
    float f3 = k;
    m = TRANSPARENT_GAP;
    float f5 = m;
    f3 -= f5;
    int n = PADDING;
    n *= 2;
    float f6 = n;
    f3 -= f6;
    f6 = i3;
    f7 = f3 / f6;
    f8 = f7;
    Matrix localMatrix2 = new android/graphics/Matrix;
    localMatrix2.<init>();
    localMatrix2.postScale(f8, f7);
    Bitmap localBitmap4 = mImgOwnerScaled;
    int i4 = 0;
    int i5 = 0;
    boolean bool2 = true;
    int i6 = i2;
    int i7 = i3;
    Bitmap localBitmap3 = Bitmap.createBitmap(localBitmap4, i4, i5, i6, i7, localMatrix2, bool2);
    mImgOwnerScaled = localBitmap3;
    localBitmap4 = mImgDogScaled;
    i4 = 0;
    i5 = 0;
    bool2 = true;
    i6 = i2;
    i7 = i3;
    localBitmap3 = Bitmap.createBitmap(localBitmap4, i4, i5, i6, i7, localMatrix2, bool2);
    mImgDogScaled = localBitmap3;
    localBitmap4 = mImgTagsScaled;
    i4 = 0;
    i5 = 0;
    localBitmap3 = mImgTagsScaled;
    i6 = localBitmap3.getWidth();
    localBitmap3 = mImgTagsScaled;
    i7 = localBitmap3.getHeight();
    bool2 = true;
    localBitmap3 = Bitmap.createBitmap(localBitmap4, i4, i5, i6, i7, localMatrix2, bool2);
    mImgTagsScaled = localBitmap3;
    localBitmap4 = mImgCollarScaled;
    i4 = 0;
    i5 = 0;
    localBitmap3 = mImgCollarScaled;
    i6 = localBitmap3.getWidth();
    localBitmap3 = mImgCollarScaled;
    i7 = localBitmap3.getHeight();
    bool2 = true;
    localBitmap3 = Bitmap.createBitmap(localBitmap4, i4, i5, i6, i7, localMatrix2, bool2);
    mImgCollarScaled = localBitmap3;
  }
  
  protected void onDetachedFromWindow()
  {
    int i = 0;
    int k = 1;
    Matrix localMatrix = null;
    Object localObject = mImgBackground;
    if (localObject != null)
    {
      localObject = mImgBackground;
      int j = i;
      int m = k;
      int n = k;
      Bitmap localBitmap = Bitmap.createBitmap((Bitmap)localObject, i, j, k, m, localMatrix, n);
      localObject = mCanvas;
      if (localObject != null)
      {
        localObject = mCanvas;
        ((Canvas)localObject).setBitmap(localBitmap);
      }
      int i1 = 0;
      mCanvas = localMatrix;
    }
    mImgBackground = localMatrix;
    mImgCashIcon = localMatrix;
    mImgCredIcon = localMatrix;
    mImgExpIcon = localMatrix;
    mWinLossIcon = localMatrix;
    mImgFoodMeter = localMatrix;
    mImgWaterMeter = localMatrix;
    mImgHealthIcon = localMatrix;
    mImgStrengthIcon = localMatrix;
    mImgAggrIcon = localMatrix;
    mImgOwnerScaled = localMatrix;
    mImgDogScaled = localMatrix;
    mImgTagsScaled = localMatrix;
    mImgCollarScaled = localMatrix;
    setBackgroundDrawable(localMatrix);
    System.gc();
  }
  
  public void onDraw(Canvas paramCanvas)
  {
    float f77 = 8.0F;
    float f76 = 3.95F;
    float f2 = 0.0F;
    float f75 = 0.5F;
    Paint localPaint6 = null;
    RefreshBitmaps();
    mCanvas = paramCanvas;
    Object localObject1 = mImgBackground;
    paramCanvas.drawBitmap((Bitmap)localObject1, f2, f2, localPaint6);
    localObject1 = mImgOwnerScaled;
    int j = PADDING;
    float f3 = j;
    int i16 = PADDING;
    float f22 = i16;
    paramCanvas.drawBitmap((Bitmap)localObject1, f3, f22, localPaint6);
    localObject1 = mPaintSubText;
    float f1 = ((Paint)localObject1).getTextSize();
    double d1 = f1;
    int i17 = PADDING;
    double d2 = i17;
    double d3 = 1.5D;
    d2 *= d3;
    d1 += d2;
    int i = (int)d1;
    Object localObject2 = mImgCashIcon;
    Bitmap localBitmap1 = mImgOwnerScaled;
    int k = localBitmap1.getWidth();
    int i18 = PADDING;
    k += i18;
    float f4 = k;
    i18 = PADDING;
    float f23 = i18;
    paramCanvas.drawBitmap((Bitmap)localObject2, f4, f23, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurOwner();
    localObject2 = ((DWOwner)localObject2).getCashStr();
    Bitmap localBitmap2 = mImgOwnerScaled;
    int m = localBitmap2.getWidth();
    int i19 = PADDING;
    m += i19;
    Bitmap localBitmap5 = mImgCashIcon;
    int i20 = localBitmap5.getWidth();
    m += i20;
    i20 = PADDING;
    m += i20;
    float f5 = m;
    float f24 = i;
    Paint localPaint1 = mPaintSubText;
    paramCanvas.drawText((String)localObject2, f5, f24, localPaint1);
    localObject2 = mImgCredIcon;
    int n = mCanvasWidth;
    float f6 = n;
    f6 /= f76;
    int i21 = PADDING;
    float f25 = i21;
    f6 += f25;
    Bitmap localBitmap6 = mImgCashIcon;
    int i22 = localBitmap6.getHeight();
    int i73 = PADDING;
    i22 += i73;
    i73 = PADDING;
    i22 += i73;
    float f26 = i22;
    paramCanvas.drawBitmap((Bitmap)localObject2, f6, f26, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurOwner();
    localObject2 = ((DWOwner)localObject2).getCredStr();
    int i1 = mCanvasWidth;
    float f7 = i1;
    f7 /= f76;
    int i23 = PADDING;
    float f27 = i23;
    f7 += f27;
    Bitmap localBitmap7 = mImgCredIcon;
    int i24 = localBitmap7.getWidth();
    float f28 = i24;
    f7 += f28;
    int i25 = PADDING;
    float f29 = i25;
    f7 += f29;
    Bitmap localBitmap8 = mImgCashIcon;
    int i26 = localBitmap8.getHeight();
    i73 = PADDING;
    i26 += i73;
    i26 += i;
    float f30 = i26;
    Paint localPaint2 = mPaintSubText;
    paramCanvas.drawText((String)localObject2, f7, f30, localPaint2);
    localObject2 = mImgExpIcon;
    Bitmap localBitmap3 = mImgOwnerScaled;
    int i2 = localBitmap3.getWidth();
    int i27 = PADDING;
    i2 += i27;
    float f8 = i2;
    Bitmap localBitmap9 = mImgCashIcon;
    int i28 = localBitmap9.getHeight();
    int i74 = PADDING;
    i28 += i74;
    i74 = PADDING;
    i28 += i74;
    float f31 = i28;
    paramCanvas.drawBitmap((Bitmap)localObject2, f8, f31, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurOwner();
    localObject2 = ((DWOwner)localObject2).getExpStr();
    Bitmap localBitmap4 = mImgOwnerScaled;
    int i3 = localBitmap4.getWidth();
    int i29 = PADDING;
    i3 += i29;
    Bitmap localBitmap10 = mImgExpIcon;
    int i30 = localBitmap10.getWidth();
    i3 += i30;
    i30 = PADDING;
    i3 += i30;
    float f9 = i3;
    Bitmap localBitmap11 = mImgCashIcon;
    int i31 = localBitmap11.getHeight();
    i74 = PADDING;
    i31 += i74;
    i31 += i;
    float f32 = i31;
    Paint localPaint3 = mPaintSubText;
    paramCanvas.drawText((String)localObject2, f9, f32, localPaint3);
    localObject2 = mImgDogScaled;
    int i4 = mCanvasWidth;
    float f10 = i4;
    f10 *= f75;
    Bitmap localBitmap12 = mImgDogScaled;
    int i32 = localBitmap12.getWidth();
    i32 /= 2;
    float f33 = i32;
    f10 -= f33;
    int i33 = PADDING;
    float f34 = i33;
    paramCanvas.drawBitmap((Bitmap)localObject2, f10, f34, localPaint6);
    localObject2 = mImgTagsScaled;
    int i5 = mCanvasWidth;
    float f11 = i5;
    f11 *= f75;
    Bitmap localBitmap13 = mImgDogScaled;
    int i34 = localBitmap13.getWidth();
    i34 /= 2;
    float f35 = i34;
    f11 -= f35;
    int i35 = TAGS_PADDING_X;
    float f36 = i35;
    f11 += f36;
    int i36 = PADDING;
    int i75 = TAGS_PADDING_Y;
    i36 += i75;
    float f37 = i36;
    paramCanvas.drawBitmap((Bitmap)localObject2, f11, f37, localPaint6);
    localObject2 = mImgCollarScaled;
    int i6 = mCanvasWidth;
    float f12 = i6;
    f12 *= f75;
    Bitmap localBitmap14 = mImgCollarScaled;
    int i37 = localBitmap14.getWidth();
    i37 /= 2;
    float f38 = i37;
    f12 -= f38;
    int i38 = TAGS_PADDING_X;
    float f39 = i38;
    f12 += f39;
    int i39 = PADDING;
    i75 = TAGS_PADDING_Y;
    i39 += i75;
    float f40 = i39;
    paramCanvas.drawBitmap((Bitmap)localObject2, f12, f40, localPaint6);
    localObject2 = mImgFoodMeter;
    int i7 = mCanvasWidth;
    float f13 = i7;
    f13 *= f75;
    Bitmap localBitmap15 = mImgDogScaled;
    int i40 = localBitmap15.getWidth();
    i40 /= 2;
    float f41 = i40;
    f13 += f41;
    int i41 = PADDING;
    float f42 = i41;
    f13 += f42;
    int i42 = PADDING;
    float f43 = i42;
    paramCanvas.drawBitmap((Bitmap)localObject2, f13, f43, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurDog();
    localObject2 = ((DWDog)localObject2).getFoodStr();
    int i8 = mCanvasWidth;
    float f14 = i8;
    f14 *= f75;
    Bitmap localBitmap16 = mImgDogScaled;
    int i43 = localBitmap16.getWidth();
    i43 /= 2;
    float f44 = i43;
    f14 += f44;
    int i44 = PADDING;
    float f45 = i44;
    f14 += f45;
    f45 = scale;
    f45 *= f77;
    int i45 = (int)f45;
    float f46 = i45;
    f14 += f46;
    int i46 = PADDING;
    Bitmap localBitmap31 = mImgFoodMeter;
    int i76 = localBitmap31.getHeight();
    i76 /= 2;
    i46 += i76;
    float f72 = 5.0F;
    float f74 = scale;
    f72 *= f74;
    int i77 = (int)f72;
    i46 += i77;
    float f47 = i46;
    Object localObject3 = mPaintMeterText;
    paramCanvas.drawText((String)localObject2, f14, f47, (Paint)localObject3);
    localObject2 = mImgWaterMeter;
    int i9 = mCanvasWidth;
    float f15 = i9;
    f15 *= f75;
    Bitmap localBitmap17 = mImgDogScaled;
    int i47 = localBitmap17.getWidth();
    i47 /= 2;
    float f48 = i47;
    f15 += f48;
    int i48 = PADDING;
    float f49 = i48;
    f15 += f49;
    int i49 = PADDING;
    localObject3 = mImgFoodMeter;
    int i78 = ((Bitmap)localObject3).getHeight();
    i49 += i78;
    i78 = PADDING;
    i49 += i78;
    float f50 = i49;
    paramCanvas.drawBitmap((Bitmap)localObject2, f15, f50, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurDog();
    localObject2 = ((DWDog)localObject2).getWaterStr();
    int i10 = mCanvasWidth;
    float f16 = i10;
    f16 *= f75;
    Bitmap localBitmap18 = mImgDogScaled;
    int i50 = localBitmap18.getWidth();
    i50 /= 2;
    float f51 = i50;
    f16 += f51;
    int i51 = PADDING;
    float f52 = i51;
    f16 += f52;
    f52 = scale;
    f52 *= f77;
    int i52 = (int)f52;
    float f53 = i52;
    f16 += f53;
    int i53 = PADDING;
    Bitmap localBitmap32 = mImgFoodMeter;
    int i79 = localBitmap32.getHeight();
    i53 += i79;
    i79 = PADDING;
    i53 += i79;
    i79 = PADDING;
    i53 += i79;
    Bitmap localBitmap33 = mImgFoodMeter;
    int i80 = localBitmap33.getHeight();
    i80 /= 2;
    i53 += i80;
    float f73 = 2.0F;
    f74 = scale;
    f73 *= f74;
    int i81 = (int)f73;
    i53 += i81;
    float f54 = i53;
    Paint localPaint4 = mPaintMeterText;
    paramCanvas.drawText((String)localObject2, f16, f54, localPaint4);
    localObject2 = mWinLossIcon;
    int i11 = mCanvasWidth;
    float f17 = i11;
    f17 *= f75;
    Bitmap localBitmap19 = mImgDogScaled;
    int i54 = localBitmap19.getWidth();
    i54 /= 2;
    float f55 = i54;
    f17 += f55;
    int i55 = PADDING;
    float f56 = i55;
    f17 += f56;
    int i56 = PADDING;
    float f57 = i56;
    f17 += f57;
    Bitmap localBitmap20 = mImgFoodMeter;
    int i57 = localBitmap20.getWidth();
    float f58 = i57;
    f17 += f58;
    int i58 = PADDING;
    float f59 = i58;
    f17 += f59;
    Bitmap localBitmap21 = mImgCashIcon;
    int i59 = localBitmap21.getHeight();
    int i82 = PADDING;
    i59 += i82;
    i82 = PADDING;
    i59 += i82;
    float f60 = i59;
    paramCanvas.drawBitmap((Bitmap)localObject2, f17, f60, localPaint6);
    localObject2 = DWApplication.getInstance();
    localObject2 = ((DWApplication)localObject2).getDWGameState();
    localObject2 = ((DWGameState)localObject2).getCurDog();
    localObject2 = ((DWDog)localObject2).getWinLossStr();
    int i12 = mCanvasWidth;
    float f18 = i12;
    f18 *= f75;
    Bitmap localBitmap22 = mImgDogScaled;
    int i60 = localBitmap22.getWidth();
    i60 /= 2;
    float f61 = i60;
    f18 += f61;
    int i61 = PADDING;
    float f62 = i61;
    f18 += f62;
    int i62 = PADDING;
    float f63 = i62;
    f18 += f63;
    Bitmap localBitmap23 = mImgFoodMeter;
    int i63 = localBitmap23.getWidth();
    float f64 = i63;
    f18 += f64;
    int i64 = PADDING;
    float f65 = i64;
    f18 += f65;
    Bitmap localBitmap24 = mWinLossIcon;
    int i65 = localBitmap24.getWidth();
    float f66 = i65;
    f18 += f66;
    int i66 = PADDING;
    float f67 = i66;
    f18 += f67;
    Bitmap localBitmap25 = mImgCashIcon;
    int i67 = localBitmap25.getHeight();
    i82 = PADDING;
    i67 += i82;
    i67 += i;
    float f68 = i67;
    Paint localPaint5 = mPaintSubText;
    paramCanvas.drawText((String)localObject2, f18, f68, localPaint5);
    localObject2 = mImgHealthIcon;
    int i13 = mCanvasWidth;
    Bitmap localBitmap26 = mImgHealthIcon;
    int i68 = localBitmap26.getWidth();
    i13 -= i68;
    i68 = PADDING;
    i13 -= i68;
    float f19 = i13;
    i68 = PADDING;
    float f69 = i68;
    paramCanvas.drawBitmap((Bitmap)localObject2, f19, f69, localPaint6);
    localObject2 = mImgStrengthIcon;
    int i14 = mCanvasWidth;
    Bitmap localBitmap27 = mImgHealthIcon;
    int i69 = localBitmap27.getWidth();
    i14 -= i69;
    i69 = PADDING;
    i14 -= i69;
    float f20 = i14;
    Bitmap localBitmap28 = mImgHealthIcon;
    int i70 = localBitmap28.getHeight();
    int i83 = PADDING;
    i70 += i83;
    i83 = PADDING;
    i70 += i83;
    float f70 = i70;
    paramCanvas.drawBitmap((Bitmap)localObject2, f20, f70, localPaint6);
    localObject2 = mImgAggrIcon;
    int i15 = mCanvasWidth;
    Bitmap localBitmap29 = mImgHealthIcon;
    int i71 = localBitmap29.getWidth();
    i15 -= i71;
    i71 = PADDING;
    i15 -= i71;
    float f21 = i15;
    Bitmap localBitmap30 = mImgHealthIcon;
    int i72 = localBitmap30.getHeight();
    i83 = PADDING;
    i72 += i83;
    i83 = PADDING;
    i72 += i83;
    Bitmap localBitmap34 = mImgStrengthIcon;
    int i84 = localBitmap34.getHeight();
    i72 += i84;
    i84 = PADDING;
    i72 += i84;
    i84 = PADDING;
    i72 += i84;
    i84 = 2;
    i72 -= i84;
    float f71 = i72;
    paramCanvas.drawBitmap((Bitmap)localObject2, f21, f71, localPaint6);
    super.onDraw(paramCanvas);
  }
  
  protected void onSizeChanged(int paramInt1, int paramInt2, int paramInt3, int paramInt4)
  {
    super.onSizeChanged(paramInt1, paramInt2, paramInt3, paramInt4);
    mCanvasWidth = paramInt1;
    mCanvasHeight = paramInt2;
    int i = paramInt1 / 2;
    mCanvasHalfWidth = i;
    i = paramInt2 / 2;
    mCanvasHalfHeight = i;
    ScaleBitmapsToScreen();
  }
  
  public boolean onTouchEvent(MotionEvent paramMotionEvent)
  {
    paramMotionEvent.getAction();
    boolean bool = true;
    return bool;
  }
}

/* Location:
 * Qualified Name:     kagegames.apps.DWBeta.StatusBarView
 * Java Class Version: 1.2 (46.0)
 * JD-Core Version:    0.7.1
 */