package org.kxml2.wap.wml;

import org.kxml2.wap.WbxmlParser;
import org.kxml2.wap.WbxmlSerializer;

public abstract class Wml
{
  public static final String[] ATTR_START_TABLE;
  public static final String[] ATTR_VALUE_TABLE;
  public static final String[] TAG_TABLE;
  
  static
  {
    int i5 = 3;
    int i4 = 2;
    int i3 = 1;
    int i2 = 0;
    Object localObject = null;
    int i = 59;
    String[] arrayOfString1 = new String[i];
    arrayOfString1[i2] = localObject;
    arrayOfString1[i3] = localObject;
    arrayOfString1[i4] = localObject;
    arrayOfString1[i5] = localObject;
    int m = 4;
    arrayOfString1[m] = localObject;
    m = 5;
    arrayOfString1[m] = localObject;
    m = 6;
    arrayOfString1[m] = localObject;
    m = 7;
    arrayOfString1[m] = localObject;
    m = 8;
    arrayOfString1[m] = localObject;
    m = 9;
    arrayOfString1[m] = localObject;
    m = 10;
    arrayOfString1[m] = localObject;
    m = 11;
    arrayOfString1[m] = localObject;
    m = 12;
    arrayOfString1[m] = localObject;
    m = 13;
    arrayOfString1[m] = localObject;
    m = 14;
    arrayOfString1[m] = localObject;
    m = 15;
    arrayOfString1[m] = localObject;
    m = 16;
    arrayOfString1[m] = localObject;
    m = 17;
    arrayOfString1[m] = localObject;
    m = 18;
    arrayOfString1[m] = localObject;
    m = 19;
    arrayOfString1[m] = localObject;
    m = 20;
    arrayOfString1[m] = localObject;
    m = 21;
    arrayOfString1[m] = localObject;
    m = 22;
    arrayOfString1[m] = localObject;
    m = 23;
    String str3 = "a";
    arrayOfString1[m] = str3;
    m = 24;
    str3 = "td";
    arrayOfString1[m] = str3;
    m = 25;
    str3 = "tr";
    arrayOfString1[m] = str3;
    m = 26;
    str3 = "table";
    arrayOfString1[m] = str3;
    m = 27;
    str3 = "p";
    arrayOfString1[m] = str3;
    m = 28;
    str3 = "postfield";
    arrayOfString1[m] = str3;
    m = 29;
    str3 = "anchor";
    arrayOfString1[m] = str3;
    m = 30;
    str3 = "access";
    arrayOfString1[m] = str3;
    m = 31;
    str3 = "b";
    arrayOfString1[m] = str3;
    m = 32;
    str3 = "big";
    arrayOfString1[m] = str3;
    m = 33;
    str3 = "br";
    arrayOfString1[m] = str3;
    m = 34;
    str3 = "card";
    arrayOfString1[m] = str3;
    m = 35;
    str3 = "do";
    arrayOfString1[m] = str3;
    m = 36;
    str3 = "em";
    arrayOfString1[m] = str3;
    m = 37;
    str3 = "fieldset";
    arrayOfString1[m] = str3;
    m = 38;
    str3 = "go";
    arrayOfString1[m] = str3;
    m = 39;
    str3 = "head";
    arrayOfString1[m] = str3;
    m = 40;
    str3 = "i";
    arrayOfString1[m] = str3;
    m = 41;
    str3 = "img";
    arrayOfString1[m] = str3;
    m = 42;
    str3 = "input";
    arrayOfString1[m] = str3;
    m = 43;
    str3 = "meta";
    arrayOfString1[m] = str3;
    m = 44;
    str3 = "noop";
    arrayOfString1[m] = str3;
    m = 45;
    str3 = "prev";
    arrayOfString1[m] = str3;
    m = 46;
    str3 = "onevent";
    arrayOfString1[m] = str3;
    m = 47;
    str3 = "optgroup";
    arrayOfString1[m] = str3;
    m = 48;
    str3 = "option";
    arrayOfString1[m] = str3;
    m = 49;
    str3 = "refresh";
    arrayOfString1[m] = str3;
    m = 50;
    str3 = "select";
    arrayOfString1[m] = str3;
    m = 51;
    str3 = "small";
    arrayOfString1[m] = str3;
    m = 52;
    str3 = "strong";
    arrayOfString1[m] = str3;
    m = 53;
    arrayOfString1[m] = localObject;
    m = 54;
    str3 = "template";
    arrayOfString1[m] = str3;
    m = 55;
    str3 = "timer";
    arrayOfString1[m] = str3;
    m = 56;
    str3 = "u";
    arrayOfString1[m] = str3;
    m = 57;
    str3 = "setvar";
    arrayOfString1[m] = str3;
    m = 58;
    str3 = "wml";
    arrayOfString1[m] = str3;
    TAG_TABLE = arrayOfString1;
    int j = 91;
    String[] arrayOfString2 = new String[j];
    String str1 = "accept-charset";
    arrayOfString2[i2] = str1;
    str1 = "align=bottom";
    arrayOfString2[i3] = str1;
    str1 = "align=center";
    arrayOfString2[i4] = str1;
    str1 = "align=left";
    arrayOfString2[i5] = str1;
    int n = 4;
    str3 = "align=middle";
    arrayOfString2[n] = str3;
    n = 5;
    str3 = "align=right";
    arrayOfString2[n] = str3;
    n = 6;
    str3 = "align=top";
    arrayOfString2[n] = str3;
    n = 7;
    str3 = "alt";
    arrayOfString2[n] = str3;
    n = 8;
    str3 = "content";
    arrayOfString2[n] = str3;
    n = 9;
    arrayOfString2[n] = localObject;
    n = 10;
    str3 = "domain";
    arrayOfString2[n] = str3;
    n = 11;
    str3 = "emptyok=false";
    arrayOfString2[n] = str3;
    n = 12;
    str3 = "emptyok=true";
    arrayOfString2[n] = str3;
    n = 13;
    str3 = "format";
    arrayOfString2[n] = str3;
    n = 14;
    str3 = "height";
    arrayOfString2[n] = str3;
    n = 15;
    str3 = "hspace";
    arrayOfString2[n] = str3;
    n = 16;
    str3 = "ivalue";
    arrayOfString2[n] = str3;
    n = 17;
    str3 = "iname";
    arrayOfString2[n] = str3;
    n = 18;
    arrayOfString2[n] = localObject;
    n = 19;
    str3 = "label";
    arrayOfString2[n] = str3;
    n = 20;
    str3 = "localsrc";
    arrayOfString2[n] = str3;
    n = 21;
    str3 = "maxlength";
    arrayOfString2[n] = str3;
    n = 22;
    str3 = "method=get";
    arrayOfString2[n] = str3;
    n = 23;
    str3 = "method=post";
    arrayOfString2[n] = str3;
    n = 24;
    str3 = "mode=nowrap";
    arrayOfString2[n] = str3;
    n = 25;
    str3 = "mode=wrap";
    arrayOfString2[n] = str3;
    n = 26;
    str3 = "multiple=false";
    arrayOfString2[n] = str3;
    n = 27;
    str3 = "multiple=true";
    arrayOfString2[n] = str3;
    n = 28;
    str3 = "name";
    arrayOfString2[n] = str3;
    n = 29;
    str3 = "newcontext=false";
    arrayOfString2[n] = str3;
    n = 30;
    str3 = "newcontext=true";
    arrayOfString2[n] = str3;
    n = 31;
    str3 = "onpick";
    arrayOfString2[n] = str3;
    n = 32;
    str3 = "onenterbackward";
    arrayOfString2[n] = str3;
    n = 33;
    str3 = "onenterforward";
    arrayOfString2[n] = str3;
    n = 34;
    str3 = "ontimer";
    arrayOfString2[n] = str3;
    n = 35;
    str3 = "optimal=false";
    arrayOfString2[n] = str3;
    n = 36;
    str3 = "optimal=true";
    arrayOfString2[n] = str3;
    n = 37;
    str3 = "path";
    arrayOfString2[n] = str3;
    n = 38;
    arrayOfString2[n] = localObject;
    n = 39;
    arrayOfString2[n] = localObject;
    n = 40;
    arrayOfString2[n] = localObject;
    n = 41;
    str3 = "scheme";
    arrayOfString2[n] = str3;
    n = 42;
    str3 = "sendreferer=false";
    arrayOfString2[n] = str3;
    n = 43;
    str3 = "sendreferer=true";
    arrayOfString2[n] = str3;
    n = 44;
    str3 = "size";
    arrayOfString2[n] = str3;
    n = 45;
    str3 = "src";
    arrayOfString2[n] = str3;
    n = 46;
    str3 = "ordered=true";
    arrayOfString2[n] = str3;
    n = 47;
    str3 = "ordered=false";
    arrayOfString2[n] = str3;
    n = 48;
    str3 = "tabindex";
    arrayOfString2[n] = str3;
    n = 49;
    str3 = "title";
    arrayOfString2[n] = str3;
    n = 50;
    str3 = "type";
    arrayOfString2[n] = str3;
    n = 51;
    str3 = "type=accept";
    arrayOfString2[n] = str3;
    n = 52;
    str3 = "type=delete";
    arrayOfString2[n] = str3;
    n = 53;
    str3 = "type=help";
    arrayOfString2[n] = str3;
    n = 54;
    str3 = "type=password";
    arrayOfString2[n] = str3;
    n = 55;
    str3 = "type=onpick";
    arrayOfString2[n] = str3;
    n = 56;
    str3 = "type=onenterbackward";
    arrayOfString2[n] = str3;
    n = 57;
    str3 = "type=onenterforward";
    arrayOfString2[n] = str3;
    n = 58;
    str3 = "type=ontimer";
    arrayOfString2[n] = str3;
    n = 59;
    arrayOfString2[n] = localObject;
    n = 60;
    arrayOfString2[n] = localObject;
    n = 61;
    arrayOfString2[n] = localObject;
    n = 62;
    arrayOfString2[n] = localObject;
    n = 63;
    arrayOfString2[n] = localObject;
    n = 64;
    str3 = "type=options";
    arrayOfString2[n] = str3;
    n = 65;
    str3 = "type=prev";
    arrayOfString2[n] = str3;
    n = 66;
    str3 = "type=reset";
    arrayOfString2[n] = str3;
    n = 67;
    str3 = "type=text";
    arrayOfString2[n] = str3;
    n = 68;
    str3 = "type=vnd.";
    arrayOfString2[n] = str3;
    n = 69;
    str3 = "href";
    arrayOfString2[n] = str3;
    n = 70;
    str3 = "href=http://";
    arrayOfString2[n] = str3;
    n = 71;
    str3 = "href=https://";
    arrayOfString2[n] = str3;
    n = 72;
    str3 = "value";
    arrayOfString2[n] = str3;
    n = 73;
    str3 = "vspace";
    arrayOfString2[n] = str3;
    n = 74;
    str3 = "width";
    arrayOfString2[n] = str3;
    n = 75;
    str3 = "xml:lang";
    arrayOfString2[n] = str3;
    n = 76;
    arrayOfString2[n] = localObject;
    n = 77;
    str3 = "align";
    arrayOfString2[n] = str3;
    n = 78;
    str3 = "columns";
    arrayOfString2[n] = str3;
    n = 79;
    str3 = "class";
    arrayOfString2[n] = str3;
    n = 80;
    str3 = "id";
    arrayOfString2[n] = str3;
    n = 81;
    str3 = "forua=false";
    arrayOfString2[n] = str3;
    n = 82;
    str3 = "forua=true";
    arrayOfString2[n] = str3;
    n = 83;
    str3 = "src=http://";
    arrayOfString2[n] = str3;
    n = 84;
    str3 = "src=https://";
    arrayOfString2[n] = str3;
    n = 85;
    str3 = "http-equiv";
    arrayOfString2[n] = str3;
    n = 86;
    str3 = "http-equiv=Content-Type";
    arrayOfString2[n] = str3;
    n = 87;
    str3 = "content=application/vnd.wap.wmlc;charset=";
    arrayOfString2[n] = str3;
    n = 88;
    str3 = "http-equiv=Expires";
    arrayOfString2[n] = str3;
    n = 89;
    arrayOfString2[n] = localObject;
    n = 90;
    arrayOfString2[n] = localObject;
    ATTR_START_TABLE = arrayOfString2;
    int k = 29;
    String[] arrayOfString3 = new String[k];
    String str2 = ".com/";
    arrayOfString3[i2] = str2;
    str2 = ".edu/";
    arrayOfString3[i3] = str2;
    str2 = ".net/";
    arrayOfString3[i4] = str2;
    str2 = ".org/";
    arrayOfString3[i5] = str2;
    int i1 = 4;
    str3 = "accept";
    arrayOfString3[i1] = str3;
    i1 = 5;
    str3 = "bottom";
    arrayOfString3[i1] = str3;
    i1 = 6;
    str3 = "clear";
    arrayOfString3[i1] = str3;
    i1 = 7;
    str3 = "delete";
    arrayOfString3[i1] = str3;
    i1 = 8;
    str3 = "help";
    arrayOfString3[i1] = str3;
    i1 = 9;
    str3 = "http://";
    arrayOfString3[i1] = str3;
    i1 = 10;
    str3 = "http://www.";
    arrayOfString3[i1] = str3;
    i1 = 11;
    str3 = "https://";
    arrayOfString3[i1] = str3;
    i1 = 12;
    str3 = "https://www.";
    arrayOfString3[i1] = str3;
    i1 = 13;
    arrayOfString3[i1] = localObject;
    i1 = 14;
    str3 = "middle";
    arrayOfString3[i1] = str3;
    i1 = 15;
    str3 = "nowrap";
    arrayOfString3[i1] = str3;
    i1 = 16;
    str3 = "onpick";
    arrayOfString3[i1] = str3;
    i1 = 17;
    str3 = "onenterbackward";
    arrayOfString3[i1] = str3;
    i1 = 18;
    str3 = "onenterforward";
    arrayOfString3[i1] = str3;
    i1 = 19;
    str3 = "ontimer";
    arrayOfString3[i1] = str3;
    i1 = 20;
    str3 = "options";
    arrayOfString3[i1] = str3;
    i1 = 21;
    str3 = "password";
    arrayOfString3[i1] = str3;
    i1 = 22;
    str3 = "reset";
    arrayOfString3[i1] = str3;
    i1 = 23;
    arrayOfString3[i1] = localObject;
    i1 = 24;
    str3 = "text";
    arrayOfString3[i1] = str3;
    i1 = 25;
    str3 = "top";
    arrayOfString3[i1] = str3;
    i1 = 26;
    str3 = "unknown";
    arrayOfString3[i1] = str3;
    i1 = 27;
    str3 = "wrap";
    arrayOfString3[i1] = str3;
    i1 = 28;
    str3 = "www.";
    arrayOfString3[i1] = str3;
    ATTR_VALUE_TABLE = arrayOfString3;
  }
  
  public static WbxmlParser createParser()
  {
    int i = 0;
    WbxmlParser localWbxmlParser = new org/kxml2/wap/WbxmlParser;
    localWbxmlParser.<init>();
    String[] arrayOfString = TAG_TABLE;
    localWbxmlParser.setTagTable(i, arrayOfString);
    arrayOfString = ATTR_START_TABLE;
    localWbxmlParser.setAttrStartTable(i, arrayOfString);
    arrayOfString = ATTR_VALUE_TABLE;
    localWbxmlParser.setAttrValueTable(i, arrayOfString);
    return localWbxmlParser;
  }
  
  public static WbxmlSerializer createSerializer()
  {
    int i = 0;
    WbxmlSerializer localWbxmlSerializer = new org/kxml2/wap/WbxmlSerializer;
    localWbxmlSerializer.<init>();
    String[] arrayOfString = TAG_TABLE;
    localWbxmlSerializer.setTagTable(i, arrayOfString);
    arrayOfString = ATTR_START_TABLE;
    localWbxmlSerializer.setAttrStartTable(i, arrayOfString);
    arrayOfString = ATTR_VALUE_TABLE;
    localWbxmlSerializer.setAttrValueTable(i, arrayOfString);
    return localWbxmlSerializer;
  }
}

/* Location:
 * Qualified Name:     org.kxml2.wap.wml.Wml
 * Java Class Version: 1.2 (46.0)
 * JD-Core Version:    0.7.1
 */